/**
 * Module Federation
 * =================
 *
 * Module Federation is a runtime module-loading mechanism that allows independently built
 * JavaScript applications to expose modules and consume modules from other applications.
 * It is commonly used as an implementation technique for micro-frontends, but it can also
 * be used for sharing libraries or other modules between independently deployed applications.
 *
 * Module Federation creates a runtime integration boundary around exposed modules. The
 * architectural quality of that boundary still depends on ownership, public contracts,
 * dependency management, version compatibility, and communication design.
 */

import { useState } from "react";
import { type FC, type ReactElement, type ReactNode } from "react";

// ---------------------------------------------------------------------
// 1. What Module Federation provides
// ---------------------------------------------------------------------

// Module Federation allows one independently built application to expose
// modules that another application can load and use at runtime.
//
// The application exposing a module is commonly called a remote.
// The application consuming it is commonly called a host.

interface FederatedApplication {
  readonly name: string;
  readonly role: "host" | "remote" | "host-and-remote";
}

const hostApplication: FederatedApplication = {
  name: "Application Shell",
  role: "host",
};

const catalogApplication: FederatedApplication = {
  name: "Catalog",
  role: "remote",
};

// ---------------------------------------------------------------------
// 2. Host and remote
// ---------------------------------------------------------------------

interface FederationRelationship {
  readonly host: string;
  readonly remote: string;
  readonly exposedModule: string;
}

const catalogRelationship: FederationRelationship = {
  host: "Application Shell",
  remote: "Catalog",
  exposedModule: "./Catalog",
};

// The host decides which remote module it wants to consume.
//
// The remote controls the implementation of the exposed module.

// ---------------------------------------------------------------------
// 3. Exposed modules
// ---------------------------------------------------------------------

interface ExposedModule {
  readonly publicName: string;
  readonly internalImplementation: string;
}

const catalogModule: ExposedModule = {
  publicName: "./Catalog",
  internalImplementation: "CatalogApplication",
};

// An exposed module is part of the remote's public integration surface.
//
// Internal components should not become exposed merely because they happen
// to be reusable.

// ---------------------------------------------------------------------
// 4. Remote entry
// ---------------------------------------------------------------------

interface RemoteEntry {
  readonly remoteName: string;
  readonly purpose: string;
}

const catalogRemoteEntry: RemoteEntry = {
  remoteName: "catalog",
  purpose: "Runtime entry point for loading exposed Catalog modules",
};

// A remote entry is generated by the Module Federation build configuration.
//
// It describes how consumers can discover the remote's exposed modules.

// ---------------------------------------------------------------------
// 5. Conceptual federation configuration
// ---------------------------------------------------------------------

interface FederationConfiguration {
  readonly name: string;
  readonly exposes: Readonly<Record<string, string>>;
  readonly remotes: Readonly<Record<string, string>>;
}

const catalogFederationConfig: FederationConfiguration = {
  name: "catalog",
  exposes: {
    "./Catalog": "./src/Catalog",
  },
  remotes: {},
};

// A remote normally declares the modules it exposes.
//
// The exact configuration syntax depends on the bundler and Module Federation
// implementation being used.

// ---------------------------------------------------------------------
// 6. Host federation configuration
// ---------------------------------------------------------------------

const shellFederationConfig: FederationConfiguration = {
  name: "shell",
  exposes: {},
  remotes: {
    catalog: "catalog@https://example.com/catalog/remoteEntry.js",
  },
};

// A host normally declares where a remote can be loaded from.
//
// The exact remote URL and runtime loading strategy depend on the build setup.

// ---------------------------------------------------------------------
// 7. Runtime loading
// ---------------------------------------------------------------------

interface RemoteLoader {
  readonly load: (moduleName: string) => Promise<unknown>;
}

const catalogLoader: RemoteLoader = {
  async load(moduleName) {
    return {
      moduleName,
    };
  },
};

// Module Federation changes the integration model from:
//
//   build-time dependency
//
// toward:
//
//   independently built module + runtime loading contract

// ---------------------------------------------------------------------
// 8. Runtime loading is not dependency inversion by itself
// ---------------------------------------------------------------------

interface RuntimeDependency {
  readonly consumer: string;
  readonly dependency: string;
  readonly coupling: string;
}

const catalogRuntimeDependency: RuntimeDependency = {
  consumer: "Application Shell",
  dependency: "Catalog remote",
  coupling: "Public runtime contract",
};

// Runtime loading changes when and how code is connected.
//
// It does not automatically create a good architectural boundary.

// ---------------------------------------------------------------------
// 9. Expose capability, not implementation
// ---------------------------------------------------------------------

interface CatalogPublicContract {
  readonly render: (products: readonly CatalogProduct[], onProductSelected: (id: string) => void) => ReactElement;
}

interface CatalogProduct {
  readonly id: string;
  readonly name: string;
  readonly price: number;
}

// The exposed module should represent a meaningful capability.
//
// Exposing dozens of internal components can turn the remote into a bag
// of implementation details.

// ---------------------------------------------------------------------
// 10. A public component contract
// ---------------------------------------------------------------------

interface CatalogComponentProps {
  readonly products: readonly CatalogProduct[];
  readonly onProductSelected: (id: string) => void;
}

export const FederatedCatalog: FC<CatalogComponentProps> = ({ products, onProductSelected }): ReactElement => {
  return (
    <section>
      <h2>Catalog</h2>
      <ul>
        {products.map((product) => (
          <li key={product.id}>
            <span>
              {product.name} — ${product.price.toFixed(2)}
            </span>
            <button onClick={() => onProductSelected(product.id)} type="button">
              Select
            </button>
          </li>
        ))}
      </ul>
    </section>
  );
};

// The host needs only this public contract.
//
// The internal implementation can change without changing the consumer.

// ---------------------------------------------------------------------
// 11. Remote implementation stays private
// ---------------------------------------------------------------------

interface CatalogSearchState {
  readonly query: string;
}

const createCatalogSearchState = (query: string): CatalogSearchState => {
  return { query };
};

// Internal state and helpers do not need to be exposed through Module Federation.

// ---------------------------------------------------------------------
// 12. Exposing a module does not mean exposing everything
// ---------------------------------------------------------------------

interface PublicSurface {
  readonly exposedModules: readonly string[];
  readonly privateModules: readonly string[];
}

const catalogPublicSurface: PublicSurface = {
  exposedModules: ["./Catalog"],
  privateModules: ["./CatalogRepository", "./CatalogSearch", "./CatalogFormatting"],
};

// Keeping the exposed surface small reduces the number of contracts
// that must remain compatible.

// ---------------------------------------------------------------------
// 13. Host composition
// ---------------------------------------------------------------------

interface HostCompositionProps {
  readonly catalog: ReactNode;
  readonly children: ReactNode;
}

export const HostComposition: FC<HostCompositionProps> = ({ catalog, children }): ReactElement => {
  return (
    <main>
      <header>
        <h1>Example Application</h1>
      </header>
      <section>{catalog}</section>
      {children}
    </main>
  );
};

// The host owns application-level composition.
//
// The remote owns the behavior and implementation of its capability.

// ---------------------------------------------------------------------
// 14. Complete host composition example
// ---------------------------------------------------------------------

export const ModuleFederationExample: FC = (): ReactElement => {
  const products: readonly CatalogProduct[] = [
    {
      id: "product-1",
      name: "Example Product",
      price: 29.99,
    },
  ];

  const handleProductSelected = (productId: string): void => {
    console.log(`Selected product: ${productId}`);
  };

  return (
    <HostComposition catalog={<FederatedCatalog onProductSelected={handleProductSelected} products={products} />}>
      <p>Account and checkout capabilities can be composed here.</p>
    </HostComposition>
  );
};

// In an actual federated application, the Catalog component could come
// from a remote module rather than being imported from the same source tree.

// ---------------------------------------------------------------------
// 15. Dynamic remote loading
// ---------------------------------------------------------------------

interface DynamicRemoteProps {
  readonly loading: boolean;
  readonly children: ReactNode;
}

export const DynamicRemote: FC<DynamicRemoteProps> = ({ loading, children }): ReactElement => {
  if (loading) {
    return <p>Loading remote...</p>;
  }

  return <>{children}</>;
};

// Runtime federation introduces loading states that do not exist
// for an ordinary statically bundled local import.

// ---------------------------------------------------------------------
// 16. Remote loading failure
// ---------------------------------------------------------------------

interface RemoteFailureProps {
  readonly failed: boolean;
  readonly children: ReactNode;
}

export const RemoteFailureBoundary: FC<RemoteFailureProps> = ({ failed, children }): ReactElement => {
  if (failed) {
    return (
      <section>
        <h2>Catalog unavailable</h2>
        <p>Please try again later.</p>
      </section>
    );
  }

  return <>{children}</>;
};

// A remote can fail independently from the host.
//
// The host therefore needs a deliberate failure strategy.

// ---------------------------------------------------------------------
// 17. Failure isolation
// ---------------------------------------------------------------------

interface RemoteFailurePolicy {
  readonly remote: string;
  readonly unrelatedFeaturesRemainUsable: boolean;
}

const catalogFailurePolicy: RemoteFailurePolicy = {
  remote: "Catalog",
  unrelatedFeaturesRemainUsable: true,
};

// A useful micro-frontend boundary prevents one remote's failure
// from unnecessarily taking down unrelated capabilities.

// ---------------------------------------------------------------------
// 18. Remote versioning
// ---------------------------------------------------------------------

interface RemoteVersion {
  readonly remote: string;
  readonly version: string;
}

const catalogRemoteVersion: RemoteVersion = {
  remote: "Catalog",
  version: "2.0.0",
};

// A remote can be deployed independently, so consumers may encounter
// different remote versions over time.

// ---------------------------------------------------------------------
// 19. Compatibility matters more than version numbers
// ---------------------------------------------------------------------

interface VersionCompatibility {
  readonly hostVersion: string;
  readonly remoteVersion: string;
  readonly contractCompatible: boolean;
}

const catalogCompatibility: VersionCompatibility = {
  hostVersion: "3.0.0",
  remoteVersion: "2.0.0",
  contractCompatible: true,
};

// Semantic compatibility is more important than identical version numbers.

// ---------------------------------------------------------------------
// 20. Breaking public changes
// ---------------------------------------------------------------------

interface ContractChange {
  readonly change: string;
  readonly breaking: boolean;
}

const catalogContractChanges: readonly ContractChange[] = [
  {
    change: "Add an optional prop",
    breaking: false,
  },
  {
    change: "Remove a required prop",
    breaking: true,
  },
  {
    change: "Rename an exposed module",
    breaking: true,
  },
  {
    change: "Change the meaning of an existing prop",
    breaking: true,
  },
];

// An exposed module is a public API.
//
// Changing it requires the same care as changing any other public contract.

// ---------------------------------------------------------------------
// 21. Consumer expectations
// ---------------------------------------------------------------------

interface ConsumerExpectation {
  readonly consumer: string;
  readonly expectedModule: string;
}

const shellExpectation: ConsumerExpectation = {
  consumer: "Application Shell",
  expectedModule: "catalog/./Catalog",
};

// The host depends on the exposed module name and its public contract,
// not on the remote's private source structure.

// ---------------------------------------------------------------------
// 22. Shared dependencies
// ---------------------------------------------------------------------

interface SharedDependency {
  readonly packageName: string;
  readonly strategy: "shared" | "bundled";
}

const reactDependency: SharedDependency = {
  packageName: "react",
  strategy: "shared",
};

// Module Federation can coordinate shared dependencies between host and remotes.

// ---------------------------------------------------------------------
// 23. Why React is commonly shared
// ---------------------------------------------------------------------

interface ReactRuntimeContract {
  readonly packageName: string;
  readonly reason: string;
}

const reactRuntimeContract: ReactRuntimeContract = {
  packageName: "react",
  reason: "Avoid unnecessary duplicate React runtimes and preserve expected React integration",
};

// React sharing can matter for hooks, context, element identity, and runtime behavior.

// ---------------------------------------------------------------------
// 24. Shared ReactDOM
// ---------------------------------------------------------------------

const reactDomDependency: SharedDependency = {
  packageName: "react-dom",
  strategy: "shared",
};

// ReactDOM may also be shared when the federation architecture requires
// a common compatible runtime environment.

// ---------------------------------------------------------------------
// 25. Singleton dependencies
// ---------------------------------------------------------------------

interface SingletonDependency {
  readonly packageName: string;
  readonly singleton: boolean;
}

const reactSingleton: SingletonDependency = {
  packageName: "react",
  singleton: true,
};

// Some dependencies are commonly configured as singletons when multiple
// runtime copies would cause incorrect or undesirable behavior.
//
// The exact configuration is bundler-specific.

// ---------------------------------------------------------------------
// 26. Version requirements
// ---------------------------------------------------------------------

interface DependencyVersionRequirement {
  readonly packageName: string;
  readonly requiredVersion: string;
}

const reactVersionRequirement: DependencyVersionRequirement = {
  packageName: "react",
  requiredVersion: "^19.0.0",
};

// Shared dependencies should have an explicit compatibility strategy.
//
// A shared package without a version policy can become a runtime risk.

// ---------------------------------------------------------------------
// 27. Dependency version drift
// ---------------------------------------------------------------------

interface VersionDrift {
  readonly packageName: string;
  readonly hostVersion: string;
  readonly remoteVersion: string;
}

const reactVersionDrift: VersionDrift = {
  packageName: "react",
  hostVersion: "19.x",
  remoteVersion: "19.x",
};

// Compatible version ranges do not guarantee that every combination
// is safe, so shared dependency policies should be tested.

// ---------------------------------------------------------------------
// 28. Shared dependency tradeoff
// ---------------------------------------------------------------------

interface SharingTradeoff {
  readonly packageName: string;
  readonly benefit: string;
  readonly cost: string;
}

const reactSharingTradeoff: SharingTradeoff = {
  packageName: "react",
  benefit: "Reduce duplication and preserve runtime identity",
  cost: "Increase version coordination",
};

// Sharing reduces duplication but increases compatibility coupling.

// ---------------------------------------------------------------------
// 29. Do not share everything
// ---------------------------------------------------------------------

const sharingDecision: readonly SharingTradeoff[] = [
  {
    packageName: "react",
    benefit: "Shared runtime identity",
    cost: "Version coordination",
  },
  {
    packageName: "date-fns",
    benefit: "Potential bundle reduction",
    cost: "Version coordination",
  },
];

// A package should be shared because there is a concrete architectural
// or performance reason, not simply because federation allows it.

// ---------------------------------------------------------------------
// 30. Shared UI libraries
// ---------------------------------------------------------------------

interface SharedUiContract {
  readonly packageName: string;
  readonly purpose: string;
}

const sharedUiContract: SharedUiContract = {
  packageName: "@example/ui",
  purpose: "Accessible application-wide UI primitives",
};

// A shared design system can provide visual consistency across remotes.

// ---------------------------------------------------------------------
// 31. Shared UI and ownership
// ---------------------------------------------------------------------

interface UiOwnership {
  readonly packageName: string;
  readonly owner: string;
}

const sharedUiOwnership: UiOwnership = {
  packageName: "@example/ui",
  owner: "Platform Team",
};

// Shared UI packages should have explicit ownership because changes
// can affect many independently deployed applications.

// ---------------------------------------------------------------------
// 32. Shared business logic
// ---------------------------------------------------------------------

interface SharedBusinessPackage {
  readonly packageName: string;
  readonly businessCapability: string;
}

const sharedBusinessPackage: SharedBusinessPackage = {
  packageName: "@example/pricing",
  businessCapability: "Pricing",
};

// Shared business logic can create strong coupling between supposedly
// independent micro-frontends.
//
// The decision should therefore be based on actual ownership and domain boundaries.

// ---------------------------------------------------------------------
// 33. Shared types
// ---------------------------------------------------------------------

interface SharedTypePackage {
  readonly packageName: string;
  readonly contents: readonly string[];
}

const sharedContractPackage: SharedTypePackage = {
  packageName: "@example/contracts",
  contents: ["Public event types", "Public API types"],
};

// Shared contracts can be useful when they represent genuine integration
// boundaries rather than internal domain models.

// ---------------------------------------------------------------------
// 34. Avoid sharing internal domain models
// ---------------------------------------------------------------------

interface InternalDomainModel {
  readonly id: string;
  readonly internalStatus: string;
  readonly internalMetadata: Record<string, unknown>;
}

// Consumers should not need this internal model merely because it is
// convenient to publish it from a shared package.

// ---------------------------------------------------------------------
// 35. Public DTO instead
// ---------------------------------------------------------------------

interface PublicProduct {
  readonly id: string;
  readonly name: string;
}

const publicProduct: PublicProduct = {
  id: "product-1",
  name: "Example Product",
};

// A public DTO creates an intentional contract between applications.

// ---------------------------------------------------------------------
// 36. Module Federation is not an API gateway
// ---------------------------------------------------------------------

interface FederationVsApi {
  readonly mechanism: string;
  readonly responsibility: string;
}

const federationResponsibility: FederationVsApi = {
  mechanism: "Module Federation",
  responsibility: "Runtime loading and module sharing",
};

const apiResponsibility: FederationVsApi = {
  mechanism: "HTTP API",
  responsibility: "Data and service communication",
};

// Module Federation solves module composition.
//
// It does not replace backend APIs, authorization, data ownership,
// or business-level service contracts.

// ---------------------------------------------------------------------
// 37. Module Federation is not a state-management system
// ---------------------------------------------------------------------

interface StateCommunication {
  readonly mechanism: string;
  readonly purpose: string;
}

const stateCommunication: StateCommunication = {
  mechanism: "Events or explicit APIs",
  purpose: "Cross-boundary state communication",
};

// Federation loads modules.
//
// It does not automatically provide a safe global state architecture.

// ---------------------------------------------------------------------
// 38. Module Federation is not a domain boundary
// ---------------------------------------------------------------------

interface DomainBoundary {
  readonly capability: string;
  readonly owner: string;
}

const catalogDomainBoundary: DomainBoundary = {
  capability: "Catalog",
  owner: "Catalog Team",
};

// A remote can expose poorly designed modules.
//
// Runtime federation does not automatically make those modules
// cohesive or independently owned.

// ---------------------------------------------------------------------
// 39. Domain boundary before runtime boundary
// ---------------------------------------------------------------------

interface ArchitectureSequence {
  readonly step: number;
  readonly activity: string;
}

const architectureSequence: readonly ArchitectureSequence[] = [
  {
    step: 1,
    activity: "Identify capability ownership",
  },
  {
    step: 2,
    activity: "Define public contracts",
  },
  {
    step: 3,
    activity: "Remove internal coupling",
  },
  {
    step: 4,
    activity: "Introduce runtime federation",
  },
];

// Module Federation should support an existing architectural boundary,
// not be used as a substitute for one.

// ---------------------------------------------------------------------
// 40. Remote ownership
// ---------------------------------------------------------------------

interface RemoteOwnership {
  readonly remote: string;
  readonly team: string;
  readonly responsibility: string;
}

const catalogOwnership: RemoteOwnership = {
  remote: "catalog",
  team: "Catalog Team",
  responsibility: "Product discovery",
};

// Independent deployment requires clear ownership of the remote.

// ---------------------------------------------------------------------
// 41. Deployment ownership
// ---------------------------------------------------------------------

interface DeploymentOwnership {
  readonly remote: string;
  readonly deployer: string;
}

const catalogDeploymentOwnership: DeploymentOwnership = {
  remote: "catalog",
  deployer: "Catalog Team",
};

// The team responsible for the remote should normally control its release process.

// ---------------------------------------------------------------------
// 42. Runtime URL ownership
// ---------------------------------------------------------------------

interface RemoteLocation {
  readonly remote: string;
  readonly location: string;
}

const catalogRemoteLocation: RemoteLocation = {
  remote: "catalog",
  location: "https://example.com/catalog/remoteEntry.js",
};

// The location of a remote is itself an operational contract.
//
// Production systems commonly use deployment infrastructure to manage
// versioned or environment-specific remote locations.

// ---------------------------------------------------------------------
// 43. Environment-specific remotes
// ---------------------------------------------------------------------

interface EnvironmentRemote {
  readonly environment: string;
  readonly location: string;
}

const environmentRemotes: readonly EnvironmentRemote[] = [
  {
    environment: "development",
    location: "https://example.com/catalog/dev/remoteEntry.js",
  },
  {
    environment: "production",
    location: "https://example.com/catalog/prod/remoteEntry.js",
  },
];

// The host can select different remote locations by environment.

// ---------------------------------------------------------------------
// 44. Runtime configuration
// ---------------------------------------------------------------------

interface RemoteManifest {
  readonly catalog: string;
  readonly account: string;
}

const remoteManifest: RemoteManifest = {
  catalog: "https://example.com/catalog/remoteEntry.js",
  account: "https://example.com/account/remoteEntry.js",
};

// A runtime manifest can decouple the host deployment from the exact
// remote location, depending on the infrastructure and federation implementation.

// ---------------------------------------------------------------------
// 45. Remote discovery
// ---------------------------------------------------------------------

interface RemoteDiscovery {
  readonly source: string;
  readonly runtimeConfigurable: boolean;
}

const remoteDiscovery: RemoteDiscovery = {
  source: "Application configuration",
  runtimeConfigurable: true,
};

// Dynamic remote discovery can support independent releases,
// but it also increases operational complexity.

// ---------------------------------------------------------------------
// 46. Security of remote loading
// ---------------------------------------------------------------------

interface RemoteSecurity {
  readonly concern: string;
  readonly mitigation: string;
}

const remoteSecurity: readonly RemoteSecurity[] = [
  {
    concern: "Untrusted remote code",
    mitigation: "Load only from controlled deployment sources",
  },
  {
    concern: "Unexpected deployment change",
    mitigation: "Use release controls and integrity verification where appropriate",
  },
];

// A federated remote executes code in the host's browser context.
//
// Remote ownership and trust therefore matter directly to application security.

// ---------------------------------------------------------------------
// 47. Remote code is application code
// ---------------------------------------------------------------------

interface RemoteTrust {
  readonly remote: string;
  readonly trustLevel: "trusted";
}

const catalogTrust: RemoteTrust = {
  remote: "catalog",
  trustLevel: "trusted",
};

// Module Federation is not a sandbox.
//
// A remote should not be treated as untrusted code simply because
// it is loaded dynamically.

// ---------------------------------------------------------------------
// 48. Iframe vs Module Federation
// ---------------------------------------------------------------------

interface IntegrationComparison {
  readonly mechanism: string;
  readonly runtimeIsolation: string;
  readonly integration: string;
}

const iframeIntegration: IntegrationComparison = {
  mechanism: "iframe",
  runtimeIsolation: "Strong",
  integration: "Browser messaging and navigation",
};

const federationIntegration: IntegrationComparison = {
  mechanism: "Module Federation",
  runtimeIsolation: "Shared page runtime",
  integration: "JavaScript module loading",
};

// Iframes isolate execution more strongly.
//
// Module Federation provides tighter in-page integration but less runtime isolation.

// ---------------------------------------------------------------------
// 49. Module Federation vs static packages
// ---------------------------------------------------------------------

const staticPackageIntegration: IntegrationComparison = {
  mechanism: "Package",
  runtimeIsolation: "None",
  integration: "Build-time dependency",
};

// A package is generally resolved during the consumer's build.
//
// A federated module can be resolved and loaded at runtime.

// ---------------------------------------------------------------------
// 50. Module Federation vs monorepo modules
// ---------------------------------------------------------------------

interface IntegrationModel {
  readonly model: string;
  readonly deploymentIndependence: boolean;
}

const monorepoModule: IntegrationModel = {
  model: "Shared source module",
  deploymentIndependence: false,
};

const federatedModule: IntegrationModel = {
  model: "Runtime federated module",
  deploymentIndependence: true,
};

// A monorepo can provide strong code organization without providing
// independent runtime deployment.

// ---------------------------------------------------------------------
// 51. Independent deployment is conditional
// ---------------------------------------------------------------------

interface IndependentDeployment {
  readonly remote: string;
  readonly independentlyDeployable: boolean;
  readonly synchronizedReleaseRequired: boolean;
}

const catalogIndependentDeployment: IndependentDeployment = {
  remote: "Catalog",
  independentlyDeployable: true,
  synchronizedReleaseRequired: false,
};

// If every remote requires simultaneous deployment with the host,
// runtime federation provides less practical independence.

// ---------------------------------------------------------------------
// 52. Distributed monolith signal
// ---------------------------------------------------------------------

interface DistributedMonolithSignal {
  readonly sharedInternalState: boolean;
  readonly synchronizedReleases: boolean;
  readonly internalImports: boolean;
}

const distributedMonolithSignal: DistributedMonolithSignal = {
  sharedInternalState: true,
  synchronizedReleases: true,
  internalImports: true,
};

// Module Federation can produce a distributed monolith if runtime separation
// is added without removing architectural coupling.

// ---------------------------------------------------------------------
// 53. Event-based communication
// ---------------------------------------------------------------------

interface ProductSelected {
  readonly type: "product-selected";
  readonly productId: string;
}

const productSelected: ProductSelected = {
  type: "product-selected",
  productId: "product-1",
};

// A remote can publish a narrow event instead of exposing its internal state.

// ---------------------------------------------------------------------
// 54. Command-based communication
// ---------------------------------------------------------------------

interface AddToCart {
  readonly productId: string;
  readonly quantity: number;
}

const addToCart: AddToCart = {
  productId: "product-1",
  quantity: 1,
};

// Commands express requested behavior.
//
// They should contain only the data required for the operation.

// ---------------------------------------------------------------------
// 55. Avoid direct remote state access
// ---------------------------------------------------------------------

interface RemoteStateAccess {
  readonly allowed: boolean;
  readonly reason: string;
}

const remoteStateAccess: RemoteStateAccess = {
  allowed: false,
  reason: "State ownership belongs to the remote",
};

// The host should not reach into a remote's internal state store.

// ---------------------------------------------------------------------
// 56. Callback boundary
// ---------------------------------------------------------------------

interface SelectionBoundaryProps {
  readonly onSelected: (productId: string) => void;
}

export const SelectionBoundary: FC<SelectionBoundaryProps> = ({ onSelected }): ReactElement => {
  return (
    <button onClick={() => onSelected("product-1")} type="button">
      Select product
    </button>
  );
};

// Callbacks are useful when the host and remote share a compatible
// component-level runtime and type contract.

// ---------------------------------------------------------------------
// 57. Event boundary
// ---------------------------------------------------------------------

interface EventBoundary {
  readonly eventName: string;
  readonly payload: string;
}

const eventBoundary: EventBoundary = {
  eventName: "product-selected",
  payload: "{ productId: string }",
};

// Events are useful when the relationship should remain looser than
// a direct component callback.

// ---------------------------------------------------------------------
// 58. URL boundary
// ---------------------------------------------------------------------

interface NavigationBoundary {
  readonly owner: string;
  readonly route: string;
}

const catalogNavigation: NavigationBoundary = {
  owner: "Catalog",
  route: "/catalog",
};

// The URL can coordinate navigation without sharing internal React state.

// ---------------------------------------------------------------------
// 59. Backend boundary
// ---------------------------------------------------------------------

interface BackendBoundary {
  readonly frontend: string;
  readonly backend: string;
}

const catalogBackendBoundary: BackendBoundary = {
  frontend: "Catalog",
  backend: "Catalog API",
};

// The remote can own its backend integration rather than requiring
// the host to understand its backend implementation.

// ---------------------------------------------------------------------
// 60. Data transformation at the remote
// ---------------------------------------------------------------------

interface BackendProduct {
  readonly id: string;
  readonly display_name: string;
  readonly unit_price: number;
}

interface CatalogViewProduct {
  readonly id: string;
  readonly name: string;
  readonly price: number;
}

const toCatalogViewProduct = (product: BackendProduct): CatalogViewProduct => {
  return {
    id: product.id,
    name: product.display_name,
    price: product.unit_price,
  };
};

// The remote can transform backend-specific data into a UI-oriented
// representation before crossing the frontend boundary.

// ---------------------------------------------------------------------
// 61. Keep backend details private
// ---------------------------------------------------------------------

interface BackendImplementationDetail {
  readonly field: string;
  readonly public: boolean;
}

const backendImplementationDetails: readonly BackendImplementationDetail[] = [
  {
    field: "display_name",
    public: false,
  },
  {
    field: "unit_price",
    public: false,
  },
];

// Consumers should not depend on backend-specific field names when
// those fields are not part of the public frontend contract.

// ---------------------------------------------------------------------
// 62. Authentication context
// ---------------------------------------------------------------------

interface AuthenticationContract {
  readonly getUserId: () => string | null;
}

const authenticationContract: AuthenticationContract = {
  getUserId: () => "user-1",
};

// A host may provide authentication services through a platform contract.

// ---------------------------------------------------------------------
// 63. Authorization remains capability-specific
// ---------------------------------------------------------------------

interface AuthorizationContract {
  readonly can: (permission: string) => boolean;
}

const checkoutAuthorization: AuthorizationContract = {
  can: (permission) => permission === "purchase",
};

// The remote should not assume that authentication implies authorization.

// ---------------------------------------------------------------------
// 64. Shared context
// ---------------------------------------------------------------------

interface ContextSharing {
  readonly context: string;
  readonly requirement: string;
}

const reactContextSharing: ContextSharing = {
  context: "AuthenticationContext",
  requirement: "Compatible shared React runtime and provider identity",
};

// React context crossing a federated boundary depends on the participating
// applications actually sharing the relevant React runtime and context instance.

// ---------------------------------------------------------------------
// 65. Context coupling
// ---------------------------------------------------------------------

interface ContextCoupling {
  readonly sharedContext: string;
  readonly couplingLevel: "high";
}

const sharedAuthContextCoupling: ContextCoupling = {
  sharedContext: "AuthenticationContext",
  couplingLevel: "high",
};

// Shared context can be convenient, but it creates a stronger runtime
// integration contract than a plain serialized event or API.

// ---------------------------------------------------------------------
// 66. Prefer explicit contracts where appropriate
// ---------------------------------------------------------------------

interface ExplicitAuthentication {
  readonly userId: string | null;
}

const explicitAuthentication: ExplicitAuthentication = {
  userId: "user-1",
};

// Passing a narrow value or service contract can reduce implicit
// runtime coupling when full context sharing is unnecessary.

// ---------------------------------------------------------------------
// 67. Remote component props
// ---------------------------------------------------------------------

interface RemoteComponentProps {
  readonly title: string;
  readonly onAction: () => void;
}

export const RemoteComponent: FC<RemoteComponentProps> = ({ title, onAction }): ReactElement => {
  return (
    <button onClick={onAction} type="button">
      {title}
    </button>
  );
};

// Component props are a natural contract when federation is used
// for React component composition.

// ---------------------------------------------------------------------
// 68. Avoid exposing large prop surfaces
// ---------------------------------------------------------------------

interface LargeRemoteProps {
  readonly user: {
    readonly id: string;
    readonly name: string;
    readonly email: string;
    readonly role: string;
    readonly preferences: Record<string, unknown>;
  };
  readonly theme: Record<string, unknown>;
  readonly featureFlags: Record<string, boolean>;
}

// A large public prop surface couples the host to many details.
//
// Prefer narrow semantic inputs.

// ---------------------------------------------------------------------
// 69. Narrow remote props
// ---------------------------------------------------------------------

interface NarrowRemoteProps {
  readonly displayName: string;
  readonly onSettingsRequested: () => void;
}

const narrowRemoteProps: NarrowRemoteProps = {
  displayName: "John Doe",
  onSettingsRequested: () => {
    console.log("Settings requested");
  },
};

// Narrow contracts are easier to evolve independently.

// ---------------------------------------------------------------------
// 70. Remote registration
// ---------------------------------------------------------------------

interface RemoteRegistration {
  readonly name: string;
  readonly entry: string;
  readonly exposes: readonly string[];
}

const catalogRegistration: RemoteRegistration = {
  name: "catalog",
  entry: "https://example.com/catalog/remoteEntry.js",
  exposes: ["./Catalog"],
};

// A registration describes the runtime relationship between the host
// and a remote.

// ---------------------------------------------------------------------
// 71. Remote discovery failure
// ---------------------------------------------------------------------

interface DiscoveryFailure {
  readonly remote: string;
  readonly fallback: string;
}

const catalogDiscoveryFailure: DiscoveryFailure = {
  remote: "catalog",
  fallback: "Display an unavailable state",
};

// Remote discovery itself can fail before the remote application executes.

// ---------------------------------------------------------------------
// 72. Remote timeout
// ---------------------------------------------------------------------

interface RemoteTimeoutPolicy {
  readonly timeoutMs: number;
  readonly behavior: string;
}

const catalogTimeoutPolicy: RemoteTimeoutPolicy = {
  timeoutMs: 5000,
  behavior: "Stop waiting and render a recoverable error state",
};

// Runtime loading should not be allowed to block the entire application
// indefinitely without an explicit policy.

// ---------------------------------------------------------------------
// 73. Retry behavior
// ---------------------------------------------------------------------

interface RetryPolicy {
  readonly maxAttempts: number;
  readonly backoff: string;
}

const catalogRetryPolicy: RetryPolicy = {
  maxAttempts: 2,
  backoff: "Exponential",
};

// Retry policies should be bounded so a broken remote does not create
// uncontrolled network activity.

// ---------------------------------------------------------------------
// 74. Remote observability
// ---------------------------------------------------------------------

interface RemoteTelemetry {
  readonly remote: string;
  readonly metrics: readonly string[];
}

const catalogTelemetry: RemoteTelemetry = {
  remote: "catalog",
  metrics: ["Load duration", "Load failures", "Render failures"],
};

// A federated architecture needs observability across both host and remote.

// ---------------------------------------------------------------------
// 75. Correlation identifiers
// ---------------------------------------------------------------------

interface CorrelationContext {
  readonly requestId: string;
  readonly remote: string;
}

const catalogCorrelationContext: CorrelationContext = {
  requestId: "request-1",
  remote: "catalog",
};

// Correlation identifiers help connect host-level failures with
// remote-level telemetry.

// ---------------------------------------------------------------------
// 76. Performance implications
// ---------------------------------------------------------------------

interface FederationPerformance {
  readonly cost: string;
  readonly mitigation: string;
}

const federationPerformance: readonly FederationPerformance[] = [
  {
    cost: "Additional network requests",
    mitigation: "Load remotes when needed",
  },
  {
    cost: "Duplicate dependencies",
    mitigation: "Share selected compatible dependencies",
  },
  {
    cost: "Remote startup work",
    mitigation: "Keep remote entry points focused",
  },
];

// Federation introduces runtime overhead that should be measured rather
// than assumed to be beneficial.

// ---------------------------------------------------------------------
// 77. Code splitting
// ---------------------------------------------------------------------

interface CodeSplittingStrategy {
  readonly remote: string;
  readonly strategy: string;
}

const catalogCodeSplitting: CodeSplittingStrategy = {
  remote: "Catalog",
  strategy: "Load catalog capability when its route is reached",
};

// Runtime federation and code splitting can work together,
// but federation does not automatically produce optimal loading behavior.

// ---------------------------------------------------------------------
// 78. Critical-path remotes
// ---------------------------------------------------------------------

interface CriticalRemote {
  readonly remote: string;
  readonly criticalForInitialRender: boolean;
}

const authenticationRemote: CriticalRemote = {
  remote: "Authentication",
  criticalForInitialRender: true,
};

// A remote on the critical path can increase startup latency.
//
// Not every capability should necessarily be loaded at application startup.

// ---------------------------------------------------------------------
// 79. Remote preloading
// ---------------------------------------------------------------------

interface PreloadStrategy {
  readonly remote: string;
  readonly trigger: string;
}

const catalogPreload: PreloadStrategy = {
  remote: "Catalog",
  trigger: "User approaches catalog navigation",
};

// Preloading can reduce interaction latency while avoiding immediate startup cost.

// ---------------------------------------------------------------------
// 80. CSS isolation
// ---------------------------------------------------------------------

interface CssStrategy {
  readonly remote: string;
  readonly strategy: string;
}

const catalogCssStrategy: CssStrategy = {
  remote: "Catalog",
  strategy: "Scoped component styles",
};

// CSS should not accidentally override another remote's implementation.

// ---------------------------------------------------------------------
// 81. DOM ownership
// ---------------------------------------------------------------------

interface DomOwnership {
  readonly remote: string;
  readonly owns: string;
}

const catalogDomOwnership: DomOwnership = {
  remote: "Catalog",
  owns: "Catalog DOM subtree",
};

// A remote should generally manage the DOM it renders rather than
// manipulating another remote's elements directly.

// ---------------------------------------------------------------------
// 82. Direct DOM access across boundaries
// ---------------------------------------------------------------------

interface DomBoundaryViolation {
  readonly directAccess: boolean;
  readonly reason: string;
}

const directDomAccess: DomBoundaryViolation = {
  directAccess: true,
  reason: "Catalog modifies Checkout DOM directly",
};

// Direct cross-boundary DOM manipulation creates hidden coupling.

// ---------------------------------------------------------------------
// 83. Custom events as an alternative
// ---------------------------------------------------------------------

interface CustomEventContract {
  readonly eventName: string;
  readonly payload: string;
}

const customEventContract: CustomEventContract = {
  eventName: "catalog:product-selected",
  payload: "{ productId: string }",
};

// Browser events can provide a framework-neutral communication mechanism
// when the architecture requires it.

// ---------------------------------------------------------------------
// 84. Module Federation and framework choice
// ---------------------------------------------------------------------

interface FrameworkBoundary {
  readonly remote: string;
  readonly framework: string;
}

const catalogFramework: FrameworkBoundary = {
  remote: "Catalog",
  framework: "React",
};

// Module Federation can technically load modules from applications
// using different frontend technologies, but component interoperability
// depends on the actual exposed contract.

// ---------------------------------------------------------------------
// 85. Framework-neutral exposed module
// ---------------------------------------------------------------------

interface FrameworkNeutralModule {
  readonly interfaceName: string;
  readonly operations: readonly string[];
}

const frameworkNeutralModule: FrameworkNeutralModule = {
  interfaceName: "CatalogMount",
  operations: ["mount", "unmount"],
};

// A DOM-oriented or framework-neutral interface can reduce coupling
// when different frameworks need to coexist.

// ---------------------------------------------------------------------
// 86. Technology independence has a cost
// ---------------------------------------------------------------------

interface TechnologyTradeoff {
  readonly benefit: string;
  readonly cost: string;
}

const frameworkIndependenceTradeoff: TechnologyTradeoff = {
  benefit: "Independent framework choices",
  cost: "More integration and interoperability work",
};

// Technology independence should be an intentional requirement,
// not an automatic goal.

// ---------------------------------------------------------------------
// 87. Shared React runtime as a deliberate choice
// ---------------------------------------------------------------------

interface RuntimeStrategy {
  readonly strategy: string;
  readonly consequence: string;
}

const sharedReactStrategy: RuntimeStrategy = {
  strategy: "Share compatible React runtime",
  consequence: "Tighter React integration",
};

// Sharing React makes React component composition easier,
// while increasing runtime compatibility requirements.

// ---------------------------------------------------------------------
// 88. Isolated React runtime
// ---------------------------------------------------------------------

const isolatedReactStrategy: RuntimeStrategy = {
  strategy: "Bundle an isolated React runtime",
  consequence: "Greater runtime independence with potential duplication",
};

// Isolated runtimes can be useful when stronger independence is required,
// but they change what can safely be shared across the boundary.

// ---------------------------------------------------------------------
// 89. Module Federation and monorepos
// ---------------------------------------------------------------------

interface RepositoryArchitecture {
  readonly sourceRepository: string;
  readonly deploymentModel: string;
}

const monorepoFederation: RepositoryArchitecture = {
  sourceRepository: "Single monorepo",
  deploymentModel: "Independently deployed remotes",
};

// A monorepo and independent deployment are separate architectural decisions.

// ---------------------------------------------------------------------
// 90. Module Federation and polyrepos
// ---------------------------------------------------------------------

const polyrepoFederation: RepositoryArchitecture = {
  sourceRepository: "Independent repositories",
  deploymentModel: "Independently deployed remotes",
};

// Module Federation can work with either repository strategy.

// ---------------------------------------------------------------------
// 91. CI contract validation
// ---------------------------------------------------------------------

interface ContractValidation {
  readonly producer: string;
  readonly validation: string;
}

const catalogCiValidation: ContractValidation = {
  producer: "Catalog",
  validation: "Validate exposed module contract before deployment",
};

// Independent deployment increases the importance of automated
// compatibility validation.

// ---------------------------------------------------------------------
// 92. Deployment rollback
// ---------------------------------------------------------------------

interface RemoteRollback {
  readonly remote: string;
  readonly strategy: string;
}

const catalogRollback: RemoteRollback = {
  remote: "Catalog",
  strategy: "Restore a previously compatible remote deployment",
};

// Rollback must account for the host and remote compatibility relationship.

// ---------------------------------------------------------------------
// 93. Host rollback
// ---------------------------------------------------------------------

interface HostRollback {
  readonly host: string;
  readonly remoteCompatibility: string;
}

const shellRollback: HostRollback = {
  host: "Application Shell",
  remoteCompatibility: "Remain compatible with active remote versions",
};

// A host rollback can still fail if it expects a contract that the
// currently deployed remote no longer provides.

// ---------------------------------------------------------------------
// 94. Compatibility windows
// ---------------------------------------------------------------------

interface CompatibilityWindow {
  readonly oldContract: string;
  readonly newContract: string;
  readonly overlap: boolean;
}

const catalogCompatibilityWindow: CompatibilityWindow = {
  oldContract: "Catalog API v1",
  newContract: "Catalog API v2",
  overlap: true,
};

// Supporting a temporary compatibility window can allow independent
// host and remote deployment without synchronized releases.

// ---------------------------------------------------------------------
// 95. Deprecation
// ---------------------------------------------------------------------

interface DeprecationPolicy {
  readonly module: string;
  readonly status: "deprecated";
  readonly replacement: string;
}

const deprecatedCatalogModule: DeprecationPolicy = {
  module: "./LegacyCatalog",
  status: "deprecated",
  replacement: "./Catalog",
};

// Public federated modules should be deprecated deliberately rather than
// removed while consumers still depend on them.

// ---------------------------------------------------------------------
// 96. Avoid excessive exposed modules
// ---------------------------------------------------------------------

interface ExposureStrategy {
  readonly remote: string;
  readonly exposedModules: readonly string[];
}

const catalogExposureStrategy: ExposureStrategy = {
  remote: "Catalog",
  exposedModules: ["./Catalog"],
};

// A small exposed surface makes ownership and compatibility easier to manage.

// ---------------------------------------------------------------------
// 97. Prefer capability-level exposure
// ---------------------------------------------------------------------

const capabilityExposure: ExposureStrategy = {
  remote: "Checkout",
  exposedModules: ["./CheckoutApplication"],
};

// Exposing a complete capability can preserve internal cohesion better
// than exposing dozens of small implementation components.

// ---------------------------------------------------------------------
// 98. Complete remote boundary
// ---------------------------------------------------------------------

interface RemoteBoundary {
  readonly name: string;
  readonly publicModules: readonly string[];
  readonly publicEvents: readonly string[];
  readonly privateState: readonly string[];
  readonly owner: string;
}

const catalogRemoteBoundary: RemoteBoundary = {
  name: "Catalog",
  publicModules: ["./Catalog"],
  publicEvents: ["product-selected"],
  privateState: ["Search state", "Catalog cache", "Internal repository state"],
  owner: "Catalog Team",
};

// This model captures the architectural intent of a federated remote:
//
// public modules and events cross the boundary;
// internal state and implementation remain private.

// ---------------------------------------------------------------------
// 99. Complete host and remote model
// ---------------------------------------------------------------------

interface FederatedArchitecture {
  readonly host: string;
  readonly remotes: readonly string[];
  readonly sharedDependencies: readonly string[];
  readonly communication: readonly string[];
}

const federatedArchitecture: FederatedArchitecture = {
  host: "Application Shell",
  remotes: ["Catalog", "Account", "Checkout"],
  sharedDependencies: ["react", "react-dom"],
  communication: ["Component contracts", "Events", "URLs", "Backend APIs"],
};

// Module Federation is one mechanism inside this larger architecture.
// It does not replace the other contracts required for a maintainable system.

// ---------------------------------------------------------------------
// 100. Final architecture example
// ---------------------------------------------------------------------

interface FederatedCatalogApplicationProps {
  readonly products: readonly CatalogProduct[];
  readonly onProductSelected: (productId: string) => void;
}

export const FederatedCatalogApplication: FC<FederatedCatalogApplicationProps> = ({
  products,
  onProductSelected,
}): ReactElement => {
  const [selectedProductId, setSelectedProductId] = useState<string | null>(null);

  const handleProductSelected = (productId: string): void => {
    setSelectedProductId(productId);
    onProductSelected(productId);
  };

  return (
    <section>
      <FederatedCatalog onProductSelected={handleProductSelected} products={products} />
      {selectedProductId !== null && <p>Selected product: {selectedProductId}</p>}
    </section>
  );
};

// The remote owns its local selection state.
//
// The host receives only the semantic product-selection event.
//
// This keeps the runtime federation mechanism separate from the
// application-level ownership boundary.

// ---------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------
// - Module Federation allows independently built applications to expose and consume modules at runtime.
// - A host consumes exposed modules, while a remote exposes modules for other applications to load.
// - Runtime loading does not automatically create a good architectural boundary.
// - Exposed modules should represent meaningful capabilities rather than arbitrary internal components.
// - Internal state, repositories, hooks, and implementation details should remain private.
// - A small exposed surface reduces compatibility and coordination costs.
// - Independent deployment requires stable public contracts and deliberate compatibility management.
// - Module Federation can share dependencies such as React, but sharing creates version and runtime coordination requirements.
// - Shared dependencies should be selected deliberately rather than shared indiscriminately.
// - Sharing React can simplify React-specific composition, context, hooks, and element interoperability when compatible runtimes are used.
// - Isolating runtimes can provide greater independence at the cost of duplication and reduced runtime integration.
// - Module Federation is a module-loading mechanism, not a replacement for APIs, state management, authentication, or domain boundaries.
// - Data ownership should remain with the capability that owns the corresponding business responsibility.
// - Events, commands, callbacks, URLs, and APIs provide different mechanisms for communication across federated boundaries.
// - Direct access to another remote's internal state, DOM, repository, or implementation creates hidden coupling.
// - Public DTOs and boundary adapters can prevent internal data models from leaking across application boundaries.
// - Loading, timeout, retry, and failure behavior are part of the runtime integration contract.
// - Remote observability should include loading, rendering, and runtime failure information with capability identity.
// - Module Federation can work with monorepos or polyrepos; repository organization and runtime deployment are separate decisions.
// - A monorepo does not prevent independent deployment, and independent deployment does not require separate repositories.
// - Contract validation and compatibility testing become increasingly important when hosts and remotes deploy independently.
// - Version compatibility is more important than identical version numbers.
// - Temporary compatibility windows and deprecation periods can allow hosts and remotes to evolve independently.
// - Security matters because federated remote code executes in the host's runtime context and is not automatically sandboxed.
// - Iframes provide stronger runtime isolation, while Module Federation provides tighter in-page JavaScript integration.
// - Module Federation can support different frontend technologies, but framework-neutral integration introduces additional interoperability work.
// - A federated architecture becomes a distributed monolith when remotes still require shared internal state, internal imports, or synchronized releases.
// - Module Federation should support deliberate capability boundaries rather than being used as a substitute for architectural boundaries.
