/**
 * Hydration Mismatch
 * ===================
 *
 * A hydration mismatch occurs when the HTML generated by the server does not match the initial
 * React output produced by the client during hydration. Mismatches can result from different
 * data, browser-only values, environment-dependent rendering, invalid HTML, or other differences
 * between the server and client environments.
 */

// ---------------------------------------------------------------------
// 1. Importing hydration APIs and client-side hooks
// ---------------------------------------------------------------------

import { hydrateRoot } from "react-dom/client";
import { useEffect, useState, type FC, type ReactElement } from "react";

// Hydration expects the initial client render to correspond to the HTML
// that was already produced by the server.

// ---------------------------------------------------------------------
// 2. A matching server and client render
// ---------------------------------------------------------------------

export const StableGreeting: FC = (): ReactElement => {
  return (
    <main>
      <h1>Hello, John Doe</h1>
      <p>Welcome to the application.</p>
    </main>
  );
};

export const hydrateStableGreeting = (container: HTMLElement): void => {
  hydrateRoot(container, <StableGreeting />);
};

// The server and client both produce the same initial markup.
// No hydration mismatch should occur.

// ---------------------------------------------------------------------
// 3. A mismatch caused by different data
// ---------------------------------------------------------------------

interface UserProps {
  readonly name: string;
}

export const UserGreeting: FC<UserProps> = ({ name }): ReactElement => {
  return <h1>Hello, {name}</h1>;
};

export const hydrateUserGreeting = (container: HTMLElement): void => {
  hydrateRoot(container, <UserGreeting name="Jane Doe" />);
};

// If the server rendered `John Doe` but the client initially renders `Jane Doe`,
// the text content differs and React detects a hydration mismatch.

// ---------------------------------------------------------------------
// 4. Fixing data mismatches by sharing the initial data
// ---------------------------------------------------------------------

export const SharedDataGreeting: FC<UserProps> = ({ name }): ReactElement => {
  return (
    <main>
      <h1>Hello, {name}</h1>
      <p>Welcome to the application.</p>
    </main>
  );
};

export const hydrateSharedDataGreeting = (container: HTMLElement, name: string): void => {
  hydrateRoot(container, <SharedDataGreeting name={name} />);
};

const initialUserName = "John Doe";

hydrateSharedDataGreeting(document.createElement("div"), initialUserName);

// The same initial value should be used to produce the server HTML
// and the initial client React tree.

// ---------------------------------------------------------------------
// 5. A mismatch caused by the current time
// ---------------------------------------------------------------------

export const CurrentTime: FC = (): ReactElement => {
  return <p>Current time: {new Date().toLocaleTimeString()}</p>;
};

export const hydrateCurrentTime = (container: HTMLElement): void => {
  hydrateRoot(container, <CurrentTime />);
};

// The server and browser execute at different times.
// `new Date()` can therefore produce different text during the two renders.

// ---------------------------------------------------------------------
// 6. Avoid time-dependent values during the initial render
// ---------------------------------------------------------------------

interface TimestampProps {
  readonly timestamp: string;
}

export const Timestamp: FC<TimestampProps> = ({ timestamp }): ReactElement => {
  return <p>Generated at: {timestamp}</p>;
};

export const hydrateTimestamp = (container: HTMLElement, timestamp: string): void => {
  hydrateRoot(container, <Timestamp timestamp={timestamp} />);
};

// The server-generated timestamp can be passed to the client so both
// environments render the same initial value.

// ---------------------------------------------------------------------
// 7. Moving browser-dependent work after hydration
// ---------------------------------------------------------------------

export const ClientOnlyStatus: FC = (): ReactElement => {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  return <p>{isClient ? "Running in the browser." : "Initial server-compatible content."}</p>;
};

export const hydrateClientOnlyStatus = (container: HTMLElement): void => {
  hydrateRoot(container, <ClientOnlyStatus />);
};

// The initial render is the same on the server and client.
// The Effect runs after hydration and changes the content only afterward.

// ---------------------------------------------------------------------
// 8. Browser-only APIs can cause mismatches
// ---------------------------------------------------------------------

export const BrowserWidth: FC = (): ReactElement => {
  return <p>Browser width: {window.innerWidth}</p>;
};

// This component is unsafe to render on the server because `window`
// does not exist in a normal server rendering environment.

// ---------------------------------------------------------------------
// 9. Rendering browser-dependent values after hydration
// ---------------------------------------------------------------------

export const SafeBrowserWidth: FC = (): ReactElement => {
  const [width, setWidth] = useState<number | null>(null);

  useEffect(() => {
    setWidth(window.innerWidth);
  }, []);

  return <p>Browser width: {width ?? "Loading..."}</p>;
};

export const hydrateSafeBrowserWidth = (container: HTMLElement): void => {
  hydrateRoot(container, <SafeBrowserWidth />);
};

// The initial output is deterministic.
// Browser-specific information is read only after hydration.

// ---------------------------------------------------------------------
// 10. Random values can cause mismatches
// ---------------------------------------------------------------------

export const RandomValue: FC = (): ReactElement => {
  return <p>Value: {Math.random()}</p>;
};

export const hydrateRandomValue = (container: HTMLElement): void => {
  hydrateRoot(container, <RandomValue />);
};

// `Math.random()` can produce different values on the server and client.
// It should not be used directly for initial hydrated markup.

// ---------------------------------------------------------------------
// 11. Generate nondeterministic values outside the initial render
// ---------------------------------------------------------------------

export const ClientRandomValue: FC = (): ReactElement => {
  const [value, setValue] = useState<number | null>(null);

  useEffect(() => {
    setValue(Math.random());
  }, []);

  return <p>Value: {value ?? "Loading..."}</p>;
};

export const hydrateClientRandomValue = (container: HTMLElement): void => {
  hydrateRoot(container, <ClientRandomValue />);
};

// The server and initial client render both display the deterministic fallback.
// The random value is generated only after hydration.

// ---------------------------------------------------------------------
// 12. Invalid HTML structure can also cause mismatches
// ---------------------------------------------------------------------

export const InvalidMarkup: FC = (): ReactElement => {
  return (
    <p>
      <div>Example content</div>
    </p>
  );
};

// Invalid HTML nesting can be parsed differently by the browser than React's
// expected tree, which can result in a hydration mismatch.

// ---------------------------------------------------------------------
// 13. Use valid HTML structure
// ---------------------------------------------------------------------

export const ValidMarkup: FC = (): ReactElement => {
  return (
    <div>
      <p>Example content</p>
    </div>
  );
};

export const hydrateValidMarkup = (container: HTMLElement): void => {
  hydrateRoot(container, <ValidMarkup />);
};

// Valid HTML gives the browser and React the same document structure to hydrate.

// ---------------------------------------------------------------------
// 14. Conditional rendering must agree during the initial render
// ---------------------------------------------------------------------

interface AccountStatusProps {
  readonly isAuthenticated: boolean;
}

export const AccountStatus: FC<AccountStatusProps> = ({ isAuthenticated }): ReactElement => {
  return <section>{isAuthenticated ? <p>Welcome back, John Doe.</p> : <p>Please sign in.</p>}</section>;
};

export const hydrateAccountStatus = (container: HTMLElement, isAuthenticated: boolean): void => {
  hydrateRoot(container, <AccountStatus isAuthenticated={isAuthenticated} />);
};

// Authentication state used during the initial client render must correspond
// to the state that produced the server HTML.

// ---------------------------------------------------------------------
// 15. Environment checks alone do not automatically solve mismatches
// ---------------------------------------------------------------------

export const EnvironmentDependentContent: FC = (): ReactElement => {
  if (typeof window === "undefined") {
    return <p>Server content.</p>;
  }

  return <p>Browser content.</p>;
};

// The server and client intentionally return different markup here.
// The environment check prevents a `window` reference error, but it does not
// make the two renders equivalent.

// ---------------------------------------------------------------------
// 16. Use an Effect when browser-only content should appear afterward
// ---------------------------------------------------------------------

export const EnvironmentAwareContent: FC = (): ReactElement => {
  const [isBrowser, setIsBrowser] = useState(false);

  useEffect(() => {
    setIsBrowser(true);
  }, []);

  return <p>{isBrowser ? "Browser content." : "Server-compatible content."}</p>;
};

export const hydrateEnvironmentAwareContent = (container: HTMLElement): void => {
  hydrateRoot(container, <EnvironmentAwareContent />);
};

// Both environments produce "Server-compatible content." initially.
// The browser-specific version appears after hydration.

// ---------------------------------------------------------------------
// 17. `suppressHydrationWarning` is an escape hatch
// ---------------------------------------------------------------------

export const UnavoidableDifference: FC = (): ReactElement => {
  return <p suppressHydrationWarning={true}>{new Date().toLocaleTimeString()}</p>;
};

export const hydrateUnavoidableDifference = (container: HTMLElement): void => {
  hydrateRoot(container, <UnavoidableDifference />);
};

// `suppressHydrationWarning` tells React not to warn about a mismatch
// on that element. It should be reserved for intentional, unavoidable differences.

// ---------------------------------------------------------------------
// 18. Do not use `suppressHydrationWarning` to hide ordinary bugs
// ---------------------------------------------------------------------

export const IncorrectlySuppressedContent: FC = (): ReactElement => {
  return (
    <main suppressHydrationWarning={true}>
      <h1>Example Application</h1>
      <p>Unexpectedly different content.</p>
    </main>
  );
};

// Suppressing a warning does not make the server and client trees equivalent.
// The underlying rendering difference should normally be fixed instead.

// ---------------------------------------------------------------------
// 19. Hydration mismatches can occur deeper in a component tree
// ---------------------------------------------------------------------

export const Header: FC = (): ReactElement => {
  return (
    <header>
      <h1>Example Application</h1>
    </header>
  );
};

export const AccountDetails: FC = (): ReactElement => {
  return (
    <section>
      <h2>Account</h2>
      <p>John Doe</p>
    </section>
  );
};

export const AccountApplication: FC = (): ReactElement => {
  return (
    <main>
      <Header />
      <AccountDetails />
    </main>
  );
};

export const hydrateAccountApplication = (container: HTMLElement): void => {
  hydrateRoot(container, <AccountApplication />);
};

// A mismatch does not have to occur at the root component itself.
// Any initial output that differs between server and client can cause a mismatch.

// ---------------------------------------------------------------------
// 20. Keep initial rendering deterministic
// ---------------------------------------------------------------------

interface Product {
  readonly name: string;
  readonly price: string;
}

interface ProductPageProps {
  readonly product: Product;
}

export const ProductPage: FC<ProductPageProps> = ({ product }): ReactElement => {
  return (
    <article>
      <h1>{product.name}</h1>
      <p>Price: {product.price}</p>
    </article>
  );
};

export const hydrateProductPage = (container: HTMLElement, product: Product): void => {
  hydrateRoot(container, <ProductPage product={product} />);
};

const product: Product = {
  name: "Example Product",
  price: "$49.99",
};

hydrateProductPage(document.createElement("div"), product);

// Deterministic props and shared initial data make it possible for the
// server and client to produce equivalent initial markup.

// ---------------------------------------------------------------------
// 21. Complete demonstration
// ---------------------------------------------------------------------

export const HydrationMismatchDemo: FC = (): ReactElement => {
  return (
    <main>
      <StableGreeting />
      <SharedDataGreeting name="John Doe" />
      <Timestamp timestamp="Example timestamp" />
      <ClientOnlyStatus />
      <SafeBrowserWidth />
      <ClientRandomValue />
      <ValidMarkup />
      <AccountStatus isAuthenticated={true} />
      <EnvironmentAwareContent />
      <UnavoidableDifference />
      <Header />
      <AccountDetails />
      <ProductPage
        product={{
          name: "Example Product",
          price: "$49.99",
        }}
      />
    </main>
  );
};

export default HydrationMismatchDemo;

// ---------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------
// - A hydration mismatch occurs when the initial client React output differs from the server HTML.
// - Server and client should use the same initial data and produce equivalent initial markup.
// - Time-dependent values such as `new Date()` can produce different output in each environment.
// - Random values such as `Math.random()` should not be generated during the initial hydrated render.
// - Browser-only APIs such as `window` should not determine different initial server and client markup.
// - Browser-dependent behavior can be moved into an Effect so it runs after hydration.
// - Invalid HTML nesting can cause the browser DOM to differ from React's expected tree.
// - Conditional rendering must use equivalent initial conditions on the server and client.
// - Environment checks can avoid browser API errors but do not by themselves prevent hydration mismatches.
// - `suppressHydrationWarning` is an escape hatch for intentional, unavoidable differences, not a general fix.
// - Keeping the initial render deterministic is the primary way to prevent hydration mismatches.
