/**
 * Render To Static Markup
 * =======================
 *
 * `renderToStaticMarkup` renders a React tree into a non-interactive HTML string on the server.
 * The output is intended for static HTML use cases such as emails, documents, and simple static
 * pages where the generated markup does not need to be hydrated into an interactive React tree.
 */

import { renderToStaticMarkup } from "react-dom/server";
import { Suspense, use, type FC, type ReactElement } from "react";

// ---------------------------------------------------------------------
// 1. Basic static rendering
// ---------------------------------------------------------------------

export const Greeting: FC = (): ReactElement => {
  return (
    <section>
      <h1>Hello, John Doe</h1>
      <p>Welcome to the example application.</p>
    </section>
  );
};

export const renderGreeting = (): string => {
  return renderToStaticMarkup(<Greeting />);
};

const greetingMarkup = renderGreeting();

console.log(greetingMarkup);

// `renderToStaticMarkup` returns an HTML string.
// The result contains the rendered markup but does not represent a live React tree.

// ---------------------------------------------------------------------
// 2. Rendering component props
// ---------------------------------------------------------------------

interface UserCardProps {
  readonly name: string;
  readonly email: string;
}

export const UserCard: FC<UserCardProps> = ({ name, email }): ReactElement => {
  return (
    <article>
      <h2>{name}</h2>
      <p>{email}</p>
    </article>
  );
};

export const renderUserCard = (name: string, email: string): string => {
  return renderToStaticMarkup(<UserCard name={name} email={email} />);
};

const userCardMarkup = renderUserCard("John Doe", "john.doe@example.com");

console.log(userCardMarkup);

// Props are resolved while React renders the component tree.
// The returned value is ordinary HTML text.

// ---------------------------------------------------------------------
// 3. Composing a static document
// ---------------------------------------------------------------------

export const Header: FC = (): ReactElement => {
  return (
    <header>
      <h1>Example Website</h1>
      <p>Static content generated by React.</p>
    </header>
  );
};

export const Article: FC = (): ReactElement => {
  return (
    <article>
      <h2>Example Article</h2>
      <p>This article is rendered as static HTML.</p>
    </article>
  );
};

export const Footer: FC = (): ReactElement => {
  return (
    <footer>
      <small>Example Company</small>
    </footer>
  );
};

export const Document: FC = (): ReactElement => {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>Example Document</title>
      </head>
      <body>
        <Header />
        <main>
          <Article />
        </main>
        <Footer />
      </body>
    </html>
  );
};

export const renderDocument = (): string => {
  return renderToStaticMarkup(<Document />);
};

// A complete React tree can be converted into a complete HTML document.
// The resulting string can then be sent, stored, or embedded by the server.

// ---------------------------------------------------------------------
// 4. Static output is not hydrated
// ---------------------------------------------------------------------

export const InteractiveButton: FC = (): ReactElement => {
  return (
    <button
      type="button"
      onClick={() => {
        console.log("Clicked");
      }}
    >
      Continue
    </button>
  );
};

export const renderInteractiveButtonAsStaticMarkup = (): string => {
  return renderToStaticMarkup(<InteractiveButton />);
};

const staticButtonMarkup = renderInteractiveButtonAsStaticMarkup();

console.log(staticButtonMarkup);

// The `onClick` function does not become an active event listener in the HTML string.
// `renderToStaticMarkup` produces non-interactive HTML and its output cannot be hydrated.

// ---------------------------------------------------------------------
// 5. Static markup versus hydratable server markup
// ---------------------------------------------------------------------

export const Application: FC = (): ReactElement => {
  return (
    <main>
      <h1>Example Application</h1>
      <button type="button">Continue</button>
    </main>
  );
};

export const renderAsStaticMarkup = (): string => {
  return renderToStaticMarkup(<Application />);
};

// Static markup is intended for output that does not need React hydration.
// A hydratable application should instead use a server rendering API whose output
// is designed to work with `hydrateRoot`.

// ---------------------------------------------------------------------
// 6. Static markup for an email
// ---------------------------------------------------------------------

interface EmailProps {
  readonly recipient: string;
  readonly message: string;
}

export const Email: FC<EmailProps> = ({ recipient, message }): ReactElement => {
  return (
    <html lang="en">
      <body>
        <main>
          <h1>Hello, {recipient}</h1>
          <p>{message}</p>
          <p>
            Regards,
            <br />
            Example Company
          </p>
        </main>
      </body>
    </html>
  );
};

export const renderEmail = (recipient: string, message: string): string => {
  return renderToStaticMarkup(<Email recipient={recipient} message={message} />);
};

const emailMarkup = renderEmail("John Doe", "Your example report is ready.");

console.log(emailMarkup);

// Email content is a natural static-markup use case because the resulting HTML
// is consumed as a document rather than hydrated into an interactive React application.

// ---------------------------------------------------------------------
// 7. Static markup for a document
// ---------------------------------------------------------------------

export const Report: FC = (): ReactElement => {
  return (
    <article>
      <h1>Example Report</h1>

      <section>
        <h2>Overview</h2>
        <p>The report contains static information.</p>
      </section>

      <section>
        <h2>Results</h2>
        <ul>
          <li>First result</li>
          <li>Second result</li>
          <li>Third result</li>
        </ul>
      </section>
    </article>
  );
};

export const renderReport = (): string => {
  return renderToStaticMarkup(<Report />);
};

// Static document generation does not require a browser DOM.
// React evaluates the component tree and produces the corresponding HTML string.

// ---------------------------------------------------------------------
// 8. Lists and dynamic content
// ---------------------------------------------------------------------

interface Product {
  readonly id: number;
  readonly name: string;
  readonly price: string;
}

const products: Product[] = [
  {
    id: 1,
    name: "Example Product",
    price: "$19.99",
  },
  {
    id: 2,
    name: "Another Product",
    price: "$29.99",
  },
  {
    id: 3,
    name: "Third Product",
    price: "$39.99",
  },
];

export const ProductList: FC = (): ReactElement => {
  return (
    <ul>
      {products.map((product) => (
        <li key={product.id}>
          <strong>{product.name}</strong>
          {" — "}
          <span>{product.price}</span>
        </li>
      ))}
    </ul>
  );
};

export const renderProductList = (): string => {
  return renderToStaticMarkup(<ProductList />);
};

// Dynamic JavaScript data can still determine the static output.
// "Static" describes the resulting HTML, not necessarily how the data was prepared.

// ---------------------------------------------------------------------
// 9. Attributes and HTML output
// ---------------------------------------------------------------------

export const AccessibleCard: FC = (): ReactElement => {
  return (
    <article aria-labelledby="card-title" data-section="example">
      <h2 id="card-title">Example Card</h2>
      <p>Static markup can contain normal HTML attributes.</p>
    </article>
  );
};

export const renderAccessibleCard = (): string => {
  return renderToStaticMarkup(<AccessibleCard />);
};

// React converts JSX properties into the corresponding HTML attributes.
// The result remains an HTML string rather than a browser DOM tree.

// ---------------------------------------------------------------------
// 10. Static markup and forms
// ---------------------------------------------------------------------

export const ContactForm: FC = (): ReactElement => {
  return (
    <form action="/contact" method="post">
      <label htmlFor="name">Name</label>
      <input id="name" name="name" type="text" />

      <label htmlFor="email">Email</label>
      <input id="email" name="email" type="email" />

      <button type="submit">Send</button>
    </form>
  );
};

export const renderContactForm = (): string => {
  return renderToStaticMarkup(<ContactForm />);
};

// Forms can be rendered as static HTML.
// Native browser form behavior can still work because the generated markup
// contains normal HTML elements, but React event handlers are not attached.

// ---------------------------------------------------------------------
// 11. Static markup and IDs
// ---------------------------------------------------------------------

export const IdentifiedContent: FC = (): ReactElement => {
  return (
    <section id="example-section">
      <h2>Example Section</h2>
      <p>This section has a normal HTML id.</p>
    </section>
  );
};

export const renderIdentifiedContent = (): string => {
  return renderToStaticMarkup(<IdentifiedContent />);
};

// `renderToStaticMarkup` can also generate IDs through React's `useId`.
// The `identifierPrefix` option can be used when multiple roots need distinct prefixes.

// ---------------------------------------------------------------------
// 12. The `identifierPrefix` option
// ---------------------------------------------------------------------

export const IdentifiedApplication: FC = (): ReactElement => {
  return (
    <main>
      <h1>Example Application</h1>
      <p>Static application content.</p>
    </main>
  );
};

export const renderWithIdentifierPrefix = (): string => {
  return renderToStaticMarkup(<IdentifiedApplication />, {
    identifierPrefix: "example-",
  });
};

// `identifierPrefix` affects IDs generated by React's `useId`.
// It is useful when multiple React roots share the same page and their generated IDs must not conflict.

// ---------------------------------------------------------------------
// 13. Static markup and Suspense
// ---------------------------------------------------------------------

const reportPromise = Promise.resolve("The report is ready.");

export const SuspendedReport: FC = (): ReactElement => {
  const message = use(reportPromise);

  return (
    <section>
      <h2>Report</h2>
      <p>{message}</p>
    </section>
  );
};

export const SuspenseReport: FC = (): ReactElement => {
  return (
    <main>
      <h1>Example Report</h1>

      <Suspense fallback={<p>Loading report...</p>}>
        <SuspendedReport />
      </Suspense>
    </main>
  );
};

export const renderSuspenseReport = (): string => {
  return renderToStaticMarkup(<SuspenseReport />);
};

// `renderToStaticMarkup` has limited Suspense support.
// If a component suspends, React immediately renders the nearest Suspense fallback
// rather than waiting for the suspended content to resolve.

// ---------------------------------------------------------------------
// 14. Suspense is not streamed by `renderToStaticMarkup`
// ---------------------------------------------------------------------

export const SlowDocument: FC = (): ReactElement => {
  return (
    <main>
      <h1>Example Document</h1>

      <Suspense fallback={<p>Loading...</p>}>
        <SuspendedReport />
      </Suspense>
    </main>
  );
};

export const renderSlowDocument = (): string => {
  return renderToStaticMarkup(<SlowDocument />);
};

// `renderToStaticMarkup` returns one complete string.
// It does not progressively send completed Suspense content as it becomes available.

// ---------------------------------------------------------------------
// 15. Static markup and hydration
// ---------------------------------------------------------------------

export const StaticPage: FC = (): ReactElement => {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>Static Page</title>
      </head>
      <body>
        <main>
          <h1>Static Page</h1>
          <p>This page is generated as non-interactive HTML.</p>
        </main>
      </body>
    </html>
  );
};

export const createStaticPage = (): string => {
  return renderToStaticMarkup(<StaticPage />);
};

// The output of `renderToStaticMarkup` cannot later be passed to `hydrateRoot`.
// If the HTML needs to become a React application in the browser, use a hydratable
// server-rendering API instead.

// ---------------------------------------------------------------------
// 16. Static HTML without React-specific hydration markers
// ---------------------------------------------------------------------

export const PlainMarkup: FC = (): ReactElement => {
  return (
    <div>
      <h1>Example Content</h1>
      <p>This output is intended to remain static.</p>
    </div>
  );
};

export const renderPlainMarkup = (): string => {
  return renderToStaticMarkup(<PlainMarkup />);
};

// The static renderer is designed to produce plain non-interactive HTML.
// It does not produce output intended to be attached to a React tree through hydration.

// ---------------------------------------------------------------------
// 17. Static rendering versus server rendering
// ---------------------------------------------------------------------

export const ServerContent: FC = (): ReactElement => {
  return (
    <main>
      <h1>Example Content</h1>
      <p>The same component can be rendered using different server APIs.</p>
    </main>
  );
};

export const renderStaticVersion = (): string => {
  return renderToStaticMarkup(<ServerContent />);
};

// `renderToStaticMarkup` is specialized for non-interactive output.
// `renderToString` is designed for HTML that may later be hydrated.
// Streaming APIs are designed for progressively sending server-rendered content.

// ---------------------------------------------------------------------
// 18. Static markup for an RSS-like document
// ---------------------------------------------------------------------

interface ArticleSummaryProps {
  readonly title: string;
  readonly description: string;
}

export const ArticleSummary: FC<ArticleSummaryProps> = ({ title, description }): ReactElement => {
  return (
    <article>
      <h2>{title}</h2>
      <p>{description}</p>
    </article>
  );
};

export const renderArticleSummary = (): string => {
  return renderToStaticMarkup(
    <ArticleSummary title="Example Article" description="An example static article summary." />,
  );
};

// Static rendering is useful when React is being used as an HTML generation tool
// rather than as the runtime for an interactive browser application.

// ---------------------------------------------------------------------
// 19. Static markup is generated on the server
// ---------------------------------------------------------------------

export const ServerGeneratedContent: FC = (): ReactElement => {
  return (
    <main>
      <h1>Server-Generated Content</h1>
      <p>React generated this HTML from a component tree.</p>
    </main>
  );
};

export const generateServerMarkup = (): string => {
  return renderToStaticMarkup(<ServerGeneratedContent />);
};

// The intended usage is on the server at the top level of an application.
// Most application components do not need to call `renderToStaticMarkup` directly.

// ---------------------------------------------------------------------
// 20. Complete static document
// ---------------------------------------------------------------------

export const StaticDocument: FC = (): ReactElement => {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="description" content="Example static document" />
        <title>Example Static Document</title>
      </head>
      <body>
        <Header />

        <main>
          <Article />
          <ProductList />
        </main>

        <Footer />
      </body>
    </html>
  );
};

export const generateStaticDocument = (): string => {
  return renderToStaticMarkup(<StaticDocument />);
};

// The returned string can be used as the complete static HTML representation
// of the React tree for a non-interactive document.

// ---------------------------------------------------------------------
// 21. Complete demonstration
// ---------------------------------------------------------------------

export const RenderToStaticMarkupDemo: FC = (): ReactElement => {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>Example Static Document</title>
      </head>
      <body>
        <header>
          <h1>Example Website</h1>
          <p>Generated as static HTML.</p>
        </header>

        <main>
          <section>
            <h2>Products</h2>
            <ProductList />
          </section>

          <section>
            <h2>Contact</h2>
            <ContactForm />
          </section>
        </main>

        <footer>
          <small>Example Company</small>
        </footer>
      </body>
    </html>
  );
};

export const generateDemoMarkup = (): string => {
  return renderToStaticMarkup(<RenderToStaticMarkupDemo />);
};

export default RenderToStaticMarkupDemo;

// ---------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------
// - `renderToStaticMarkup` renders a React tree into a non-interactive HTML string.
// - It is imported from `react-dom/server`.
// - The API is intended for static HTML generation such as documents, emails, and simple static pages.
// - The returned value is an HTML string, not a browser DOM node.
// - Event handlers are not attached to the generated HTML.
// - Output from `renderToStaticMarkup` cannot be hydrated with `hydrateRoot`.
// - Use a hydratable server-rendering API when the generated HTML must become an interactive React application.
// - `renderToStaticMarkup` has limited Suspense support and renders a Suspense fallback when content suspends.
// - `renderToStaticMarkup` does not progressively stream Suspense content as it becomes available.
// - `identifierPrefix` can be used to prefix IDs generated by React's `useId`.
// - Static output can still contain normal HTML elements, attributes, forms, links, and other browser-native behavior.
// - "Static" describes the generated HTML output; the data used to produce that output can still be dynamic.
// - `renderToStaticMarkup` is a specialized server API for producing HTML that does not need React hydration.
