/**
 * Content Security Policy (CSP)
 * ==============================
 *
 * Content Security Policy (CSP) is a browser-enforced security mechanism that restricts which
 * scripts, styles, images, connections, frames, and other resources a document may load or execute.
 * A strong CSP provides defense in depth against attacks such as XSS, but it does not replace safe
 * rendering, input validation, HTML sanitization, or other application security controls.
 *
 * CSP is normally delivered through an HTTP response header. React components can demonstrate
 * CSP-related concepts, but the actual policy is enforced by the browser from the server's
 * response headers rather than by React itself.
 */

import { type FC, type ReactElement } from "react";

// ---------------------------------------------------------------------
// 1. CSP is a browser policy
// ---------------------------------------------------------------------

// A Content Security Policy is normally delivered through an HTTP response
// header:
//
// Content-Security-Policy: default-src 'self';
//
// The browser applies the policy to the document.
//
// React does not enforce the CSP. React runs within a document whose
// resources are subject to the browser's CSP.

// ---------------------------------------------------------------------
// 2. `default-src`
// ---------------------------------------------------------------------

// `default-src` provides a fallback policy for several resource types when
// a more specific directive is not present.
//
// Example:
//
// Content-Security-Policy: default-src 'self';
//
// This means resources covered by the policy are generally restricted to
// the document's own origin unless a more specific directive changes that
// behavior.
//
// A production policy normally defines important resource types explicitly
// according to the application's architecture.

// ---------------------------------------------------------------------
// 3. `script-src`
// ---------------------------------------------------------------------

// `script-src` controls which JavaScript sources may execute or be loaded.
//
// Example:
//
// Content-Security-Policy:
//     script-src 'self';
//
// This permits scripts from the document's own origin while restricting
// scripts from other sources.
//
// The exact policy must match the application's actual script-loading model.

// ---------------------------------------------------------------------
// 4. Blocking inline JavaScript
// ---------------------------------------------------------------------

// A CSP such as:
//
// Content-Security-Policy:
//     script-src 'self';
//
// does not permit arbitrary inline JavaScript.
//
// For example, an inline script:
//
// <script>
//     console.log("Hello");
// </script>
//
// is blocked unless the policy explicitly authorizes that particular inline
// script with a nonce or hash.
//
// Blocking inline JavaScript is an important part of a strict CSP.

// ---------------------------------------------------------------------
// 5. React event handlers and CSP
// ---------------------------------------------------------------------

// React event handlers are represented as functions:
//
// const handleClick = (): void => {
//     // application logic
// };
//
// return <button onClick={handleClick}>Save</button>;
//
// This is different from an HTML inline event-handler attribute:
//
// <button onclick="save()">Save</button>
//
// A strict CSP can block inline event-handler attributes.
//
// React's event system therefore fits naturally with a CSP that disallows
// inline JavaScript.

// ---------------------------------------------------------------------
// 6. `'unsafe-inline'`
// ---------------------------------------------------------------------

// A policy can explicitly allow inline scripts with:
//
// script-src 'unsafe-inline';
//
// However, allowing arbitrary inline JavaScript weakens the XSS protection
// provided by CSP.
//
// A stronger design normally uses nonces or hashes when inline scripts are
// genuinely required.
//
// Do not add `'unsafe-inline'` simply to make CSP errors disappear.

// ---------------------------------------------------------------------
// 7. Nonces
// ---------------------------------------------------------------------

// A nonce is a cryptographically strong, unpredictable value generated by
// the server for a particular HTTP response.
//
// Example header:
//
// Content-Security-Policy:
//     script-src 'nonce-RANDOM_VALUE';
//
// The corresponding authorized script receives the same nonce:
//
// <script nonce="RANDOM_VALUE">
//     // authorized script
// </script>
//
// The browser executes the script only when the nonce matches the policy.
//
// A nonce must not be hard-coded into the application source.

// ---------------------------------------------------------------------
// 8. Nonces must be generated per response
// ---------------------------------------------------------------------

// Conceptually:
//
// request
//   ↓
// server generates random nonce
//   ↓
// CSP header contains nonce
//   ↓
// authorized script receives same nonce
//   ↓
// browser verifies the match
//
// A nonce should be unpredictable and different for each HTTP response.
//
// This is why nonce-based CSPs generally require dynamic server-side HTML
// generation or another mechanism capable of coordinating the nonce between
// the response header and authorized script elements.

// ---------------------------------------------------------------------
// 9. React and CSP nonces
// ---------------------------------------------------------------------

interface NonceExampleProps {
  readonly nonce: string;
}

const NonceExample: FC<NonceExampleProps> = ({ nonce }): ReactElement => {
  return (
    <section>
      <p>Nonce: {nonce}</p>
    </section>
  );
};

// A React component can receive a nonce as data, but this component does not
// establish CSP enforcement.
//
// The actual CSP header still has to be generated by the server, and the
// nonce must correspond to the value authorized by that response's policy.

// ---------------------------------------------------------------------
// 10. Do not generate CSP nonces in React
// ---------------------------------------------------------------------

// This is not an appropriate design:
//
// const nonce = crypto.randomUUID();
//
// The browser must compare the nonce against the value in the HTTP response's
// CSP header. Generating a value independently inside a React component does
// not establish that relationship.
//
// The server or framework responsible for the HTML response must coordinate
// the nonce and CSP header.

// ---------------------------------------------------------------------
// 11. Hash-based CSP
// ---------------------------------------------------------------------

// A CSP can authorize a specific inline script using a cryptographic hash.
//
// Example:
//
// Content-Security-Policy:
//     script-src 'sha256-BASE64_HASH';
//
// The browser computes the hash of the inline script and executes it only
// when the result matches the policy.
//
// Hash-based CSPs can be useful when the HTML and inline script content are
// stable and can therefore be hashed ahead of time.

// ---------------------------------------------------------------------
// 12. Nonces versus hashes
// ---------------------------------------------------------------------

// Nonce-based CSP:
//
// script-src 'nonce-RANDOM_VALUE';
//
// Useful when the server dynamically generates the response.
//
// Hash-based CSP:
//
// script-src 'sha256-HASH_VALUE';
//
// Useful when authorized inline script content is stable and can be hashed
// as part of the deployment process.
//
// The choice depends on the application's rendering and deployment model.

// ---------------------------------------------------------------------
// 13. `strict-dynamic`
// ---------------------------------------------------------------------

// `'strict-dynamic'` can extend trust from a nonce- or hash-authorized script
// to scripts that it dynamically loads.
//
// Example:
//
// Content-Security-Policy:
//     script-src 'nonce-RANDOM_VALUE' 'strict-dynamic';
//
// This can be useful for applications whose trusted bootstrap script loads
// additional scripts dynamically.
//
// Its behavior changes how traditional host allowlists such as `'self'` are
// interpreted in browsers that support `strict-dynamic`, so it should be
// introduced deliberately rather than copied into a policy without testing.

// ---------------------------------------------------------------------
// 14. Strict CSP
// ---------------------------------------------------------------------

// A strict CSP commonly uses a nonce or hash rather than a large list of
// trusted domains.
//
// A simplified conceptual policy is:
//
// Content-Security-Policy:
//     script-src 'nonce-RANDOM_VALUE';
//     object-src 'none';
//     base-uri 'none';
//
// This focuses script execution on explicitly authorized scripts rather
// than trying to enumerate every domain that might load JavaScript.
//
// A real application usually needs additional directives for its resources.

// ---------------------------------------------------------------------
// 15. `object-src`
// ---------------------------------------------------------------------

// `object-src` controls resources loaded through `<object>`, `<embed>`, and
// related mechanisms.
//
// A strict policy can disable these mechanisms:
//
// object-src 'none';
//
// This reduces the browser's available attack surface when the application
// does not require object or plugin content.

// ---------------------------------------------------------------------
// 16. `base-uri`
// ---------------------------------------------------------------------

// `base-uri` controls which URLs may be used as the document's `<base>` URL.
//
// A strict policy can disable the base element:
//
// base-uri 'none';
//
// This prevents an attacker from changing how relative URLs are resolved
// through an injected `<base>` element.

// ---------------------------------------------------------------------
// 17. `style-src`
// ---------------------------------------------------------------------

// `style-src` controls where styles may originate.
//
// Example:
//
// Content-Security-Policy:
//     style-src 'self';
//
// Inline styles are also subject to CSP rules.
//
// If inline styles are genuinely required, CSP can authorize them using a
// nonce or hash rather than allowing all inline styles.

// ---------------------------------------------------------------------
// 18. Images
// ---------------------------------------------------------------------

// `img-src` controls image sources.
//
// Example:
//
// Content-Security-Policy:
//     img-src 'self' https://images.example.com;
//
// This permits images from the application's own origin and the explicitly
// allowed image origin.
//
// Resource policies should contain only sources the application actually
// needs.

// ---------------------------------------------------------------------
// 19. Connections
// ---------------------------------------------------------------------

// `connect-src` controls destinations used by APIs and other programmatic
// network connections such as fetch and WebSocket connections.
//
// Example:
//
// Content-Security-Policy:
//     connect-src 'self' https://api.example.com;
//
// This can restrict which origins browser-side application code can contact.

// ---------------------------------------------------------------------
// 20. Fonts
// ---------------------------------------------------------------------

// `font-src` controls the sources from which fonts may be loaded.
//
// Example:
//
// Content-Security-Policy:
//     font-src 'self' https://fonts.example.com;
//
// If the application serves fonts locally, a narrower policy may be possible:
//
// font-src 'self';

// ---------------------------------------------------------------------
// 21. Frames
// ---------------------------------------------------------------------

// `frame-src` controls which sources the document may embed in frames.
//
// Example:
//
// Content-Security-Policy:
//     frame-src 'self' https://player.example.com;
//
// This is useful when an application intentionally embeds external content
// such as a video player.
//
// If frames are unnecessary, a restrictive policy is preferable.

// ---------------------------------------------------------------------
// 22. `frame-ancestors`
// ---------------------------------------------------------------------

// `frame-ancestors` controls which other documents are allowed to embed the
// current document.
//
// Example:
//
// Content-Security-Policy:
//     frame-ancestors 'self';
//
// This is an important clickjacking defense.
//
// It is distinct from `frame-src`:
//
// - `frame-src` controls what this document can embed.
// - `frame-ancestors` controls who can embed this document.

// ---------------------------------------------------------------------
// 23. CSP and clickjacking
// ---------------------------------------------------------------------

// An application that should never be embedded can use:
//
// Content-Security-Policy:
//     frame-ancestors 'none';
//
// This prevents the page from being embedded by any other origin.
//
// CSP is therefore useful not only for script restrictions but also for
// controlling document embedding.

// ---------------------------------------------------------------------
// 24. `form-action`
// ---------------------------------------------------------------------

// `form-action` restricts the destinations to which forms may submit.
//
// Example:
//
// Content-Security-Policy:
//     form-action 'self';
//
// This can prevent an injected form from submitting sensitive information
// to an unexpected external destination.

// ---------------------------------------------------------------------
// 25. `upgrade-insecure-requests`
// ---------------------------------------------------------------------

// `upgrade-insecure-requests` instructs the browser to upgrade insecure
// resource requests from HTTP to HTTPS where applicable.
//
// Example:
//
// Content-Security-Policy:
//     upgrade-insecure-requests;
//
// This can help migrate applications away from insecure resource URLs.
//
// It does not replace a complete HTTPS deployment or other transport-security
// controls.

// ---------------------------------------------------------------------
// 26. Report-only mode
// ---------------------------------------------------------------------

// CSP can first be deployed in report-only mode:
//
// Content-Security-Policy-Report-Only:
//     default-src 'self';
//
// Violations are reported without enforcing the policy.
//
// This is useful during deployment because an application can discover
// legitimate resources that would otherwise be blocked before switching to
// an enforcing `Content-Security-Policy` header.

// ---------------------------------------------------------------------
// 27. Enforcing versus report-only CSP
// ---------------------------------------------------------------------

// Enforcing:
//
// Content-Security-Policy: default-src 'self';
//
// Browser behavior is restricted according to the policy.
//
// Report-only:
//
// Content-Security-Policy-Report-Only: default-src 'self';
//
// The browser observes violations and can report them, but does not block
// the resources because of the report-only policy.
//
// Report-only mode is therefore a testing and rollout mechanism, not a
// substitute for an enforcing policy.

// ---------------------------------------------------------------------
// 28. CSP violation reports
// ---------------------------------------------------------------------

// Applications can configure reporting so that CSP violations can be
// collected and analyzed.
//
// Modern deployments can use the `report-to` mechanism together with the
// Reporting API.
//
// Example concept:
//
// Content-Security-Policy:
//     default-src 'self';
//     report-to csp-endpoint;
//
// The exact reporting configuration belongs to the server and deployment
// infrastructure rather than to an individual React component.

// ---------------------------------------------------------------------
// 29. CSP does not replace React escaping
// ---------------------------------------------------------------------

const NormalReactRendering: FC = (): ReactElement => {
  const content = "<strong>Untrusted content</strong>";

  return <p>{content}</p>;
};

// React's normal JSX escaping should still be used.
//
// CSP is defense in depth. It should not be used as a reason to render
// untrusted content through unsafe HTML sinks.

// ---------------------------------------------------------------------
// 30. CSP does not replace HTML sanitization
// ---------------------------------------------------------------------

interface RichContentProps {
  readonly html: string;
}

const RichContent: FC<RichContentProps> = ({ html }): ReactElement => {
  // An actual application should sanitize untrusted HTML before it reaches
  // this sink.
  //
  // CSP can reduce the impact of some XSS attacks, but it is not a general
  // replacement for HTML sanitization.
  return <div dangerouslySetInnerHTML={{ __html: html }} />;
};

// Security controls operate at different layers:
//
// React escaping
//      ↓
// HTML sanitization
//      ↓
// URL validation
//      ↓
// CSP
//
// No single layer should be treated as a universal replacement for the others.

// ---------------------------------------------------------------------
// 31. CSP does not validate application data
// ---------------------------------------------------------------------

interface UserInputProps {
  readonly value: string;
}

const ValidatedDataExample: FC<UserInputProps> = ({ value }): ReactElement => {
  return <p>{value}</p>;
};

// CSP controls browser resource execution and loading.
//
// It does not validate:
//
// - usernames,
// - prices,
// - database records,
// - API payloads,
// - authorization decisions,
// - business rules.
//
// Application-level validation remains necessary.

// ---------------------------------------------------------------------
// 32. Avoid `'unsafe-eval'` when possible
// ---------------------------------------------------------------------

// CSP can explicitly permit string-to-code execution:
//
// script-src 'self' 'unsafe-eval';
//
// This weakens CSP's protection against JavaScript execution through APIs
// such as:
//
// - eval()
// - Function()
// - string-based setTimeout()
// - string-based setInterval()
//
// Avoid `'unsafe-eval'` unless a specific dependency genuinely requires it
// and the associated security tradeoff has been deliberately accepted.

// ---------------------------------------------------------------------
// 33. CSP and development tooling
// ---------------------------------------------------------------------

// Development tooling may use mechanisms that production policies do not
// permit, such as development servers, source maps, WebSocket connections,
// or other development-only resources.
//
// Therefore:
//
// development CSP
//        ≠
// production CSP
//
// The production policy should be tested against the production build and
// production resource-loading model.

// ---------------------------------------------------------------------
// 34. Third-party scripts
// ---------------------------------------------------------------------

// Third-party scripts should be treated as part of the application's trust
// boundary.
//
// A policy such as:
//
// script-src 'self' https://analytics.example.com;
//
// explicitly allows scripts from that origin.
//
// However, adding a domain to `script-src` means scripts from that source
// are trusted by the browser under the policy.
//
// Third-party scripts should therefore be minimized and reviewed carefully.

// ---------------------------------------------------------------------
// 35. CSP and supply-chain risk
// ---------------------------------------------------------------------

// CSP can reduce some consequences of injected or unexpected script content,
// but it cannot make a compromised trusted script trustworthy.
//
// If an allowed third-party script is compromised, the CSP may still permit
// it because the policy intentionally authorized that source.
//
// Dependency security, integrity controls, and vendor review remain important.

// ---------------------------------------------------------------------
// 36. Subresource Integrity
// ---------------------------------------------------------------------

// Subresource Integrity (SRI) can verify the expected cryptographic hash of
// externally loaded resources.
//
// Example:
//
// <script
//     src="https://cdn.example.com/library.js"
//     integrity="sha384-HASH"
//     crossorigin="anonymous"
// ></script>
//
// SRI and CSP solve different problems:
//
// - CSP controls which sources are permitted.
// - SRI verifies the contents of a particular external resource.
//
// They can be used together when the deployment model supports them.

// ---------------------------------------------------------------------
// 37. CSP configuration belongs to the server
// ---------------------------------------------------------------------

// A React component cannot reliably establish the application's complete CSP
// merely by rendering:
//
// <meta
//     httpEquiv="Content-Security-Policy"
//     content="default-src 'self'"
// />
//
// CSP is most appropriately delivered as an HTTP response header, especially
// for security-sensitive policies and deployment-wide control.
//
// Server and framework configuration should define the authoritative policy.

// ---------------------------------------------------------------------
// 38. Example policy
// ---------------------------------------------------------------------

// A simplified example policy might look like:
//
// Content-Security-Policy:
//     default-src 'self';
//     script-src 'self' 'nonce-RANDOM_VALUE';
//     style-src 'self' 'nonce-RANDOM_VALUE';
//     img-src 'self' https://images.example.com;
//     connect-src 'self' https://api.example.com;
//     font-src 'self';
//     object-src 'none';
//     base-uri 'none';
//     frame-ancestors 'self';
//     form-action 'self';
//     upgrade-insecure-requests;
//
// This is an illustrative policy, not a universal production configuration.
//
// Every source should be justified by an actual application requirement.

// ---------------------------------------------------------------------
// 39. Policy design process
// ---------------------------------------------------------------------

// A practical CSP rollout can follow this sequence:
//
// 1. Inventory scripts, styles, images, fonts, connections, frames, and forms.
// 2. Build a restrictive report-only policy.
// 3. Observe legitimate CSP violations.
// 4. Remove unnecessary resources and dependencies.
// 5. Replace unsafe inline patterns.
// 6. Add nonces or hashes where required.
// 7. Restrict remaining resource sources.
// 8. Test the production build.
// 9. Switch to the enforcing `Content-Security-Policy` header.
// 10. Continue monitoring for unexpected violations.

// ---------------------------------------------------------------------
// 40. Integrated example
// ---------------------------------------------------------------------

interface SecurityStatusProps {
  readonly policy: string;
}

const SecurityStatus: FC<SecurityStatusProps> = ({ policy }): ReactElement => {
  return (
    <section>
      <h2>Content Security Policy</h2>
      <p>{policy}</p>
    </section>
  );
};

const ContentSecurityPolicyDemo: FC = (): ReactElement => {
  const policy = "default-src 'self'; object-src 'none'; base-uri 'none';";

  return (
    <section>
      <SecurityStatus policy={policy} />
    </section>
  );
};

// The component displays a policy as application data.
//
// It does not enforce the policy.
//
// Actual enforcement requires the browser to receive the CSP through the
// appropriate HTTP response configuration.

// ---------------------------------------------------------------------
// 41. Security review checklist
// ---------------------------------------------------------------------

// When reviewing a CSP, ask:
//
// 1. Is the policy actually enforced with `Content-Security-Policy`?
// 2. Was report-only mode used during rollout?
// 3. Are scripts restricted with a nonce- or hash-based strategy where practical?
// 4. Is `'unsafe-inline'` avoided unless there is a deliberate reason?
// 5. Is `'unsafe-eval'` avoided?
// 6. Are `object-src 'none'` and `base-uri 'none'` appropriate?
// 7. Are image, font, connection, frame, and style sources intentionally restricted?
// 8. Are third-party script sources necessary and trusted?
// 9. Are `frame-ancestors` and `form-action` configured where appropriate?
// 10. Does the policy match the production build rather than only development?
// 11. Are CSP violations monitored?
// 12. Does the application still use safe React rendering and HTML sanitization?

// ---------------------------------------------------------------------
// 42. Practical guidance
// ---------------------------------------------------------------------

// CSP should be treated as defense in depth.
//
// A strong security architecture combines:
//
// safe React rendering
//      +
// context-appropriate validation
//      +
// HTML sanitization when required
//      +
// secure URL handling
//      +
// Content Security Policy
//      +
// dependency and supply-chain security
//
// Start with the narrowest policy the application can actually support,
// test it in report-only mode, then enforce it after legitimate resource
// requirements have been identified.

// ---------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------
// - Content Security Policy is a browser-enforced security mechanism delivered primarily through HTTP response headers.
// - CSP restricts which scripts, styles, images, connections, frames, forms, and other resources a document may use.
// - `default-src` provides a fallback policy for several resource types.
// - `script-src` controls JavaScript execution and script sources.
// - Strict CSPs commonly use nonces or hashes instead of broad source allowlists.
// - CSP nonces should be unpredictable and generated for each HTTP response.
// - Hash-based policies authorize specific inline script or style content by cryptographic hash.
// - `strict-dynamic` can extend trust from an authorized nonce- or hash-based script to scripts it dynamically loads.
// - `'unsafe-inline'` weakens script restrictions and should not be added merely to silence CSP errors.
// - `'unsafe-eval'` weakens protection against string-to-code execution and should generally be avoided.
// - `object-src 'none'` can disable unnecessary object and plugin content.
// - `base-uri 'none'` can prevent injected `<base>` elements from changing relative URL resolution.
// - `frame-ancestors` controls which documents may embed the current page and can help prevent clickjacking.
// - `form-action` can restrict where forms are allowed to submit.
// - `Content-Security-Policy-Report-Only` allows a policy to be tested without blocking resources.
// - CSP does not replace React's JSX escaping, HTML sanitization, URL validation, or server-side validation.
// - CSP does not make a compromised trusted third-party script trustworthy.
// - Subresource Integrity and CSP can provide complementary protection for external resources.
// - CSP configuration belongs primarily to the server and deployment infrastructure, not individual React components.
// - A production CSP should be derived from actual application resource requirements and continuously monitored.

export default ContentSecurityPolicyDemo;
