/**
 * HTTP Form Data
 * ===============
 *
 * FormData represents a set of key-value pairs that can be used to construct
 * form submissions and HTTP request bodies. It supports string values and
 * File or Blob values, making it suitable for forms that contain both regular
 * fields and uploaded files.
 *
 * The Fetch API accepts a FormData instance as a request body. When FormData
 * is used directly, the browser encodes it as multipart/form-data and
 * generates the multipart boundary required to separate individual fields.
 * Application code should not manually set the Content-Type header for a
 * FormData request because the boundary generated by the browser must match
 * the encoded body.
 *
 * FormData provides methods such as append(), set(), get(), getAll(), has(),
 * and delete(). append() adds another value without removing existing values,
 * while set() replaces all existing values for the specified key with the
 * supplied value.
 *
 * FormData values can be strings, Blob objects, or File objects. A File is a
 * specialized Blob that includes file metadata such as a name and last
 * modified timestamp. FormData can therefore represent multipart forms that
 * contain both textual fields and binary file data.
 *
 * FormData can also be constructed from an HTMLFormElement. In that case,
 * successful form controls are included according to HTML form submission
 * rules. Disabled controls and controls without a successful name/value pair
 * are not automatically included.
 *
 * FormData is different from URLSearchParams. URLSearchParams is appropriate
 * for URL-encoded textual form data, while FormData is designed for multipart
 * form submissions and can carry files or other Blob values.
 */

import { type FC, type ReactNode } from "react";

// ---------------------------------------------------------------------
// 1. Interface Definitions
// ---------------------------------------------------------------------

export interface HttpFormDataBasicProps {
  readonly name: string;
  readonly email: string;
}

export interface HttpFormDataAppendProps {
  readonly firstValue: string;
  readonly secondValue: string;
}

export interface HttpFormDataSetProps {
  readonly initialValue: string;
  readonly replacementValue: string;
}

export interface HttpFormDataGetProps {
  readonly name: string;
  readonly email: string;
}

export interface HttpFormDataFileProps {
  readonly fileName: string;
  readonly fileContent: string;
}

export interface HttpFormDataBlobProps {
  readonly content: string;
  readonly fileName: string;
}

export interface HttpFormDataRequestProps {
  readonly url: string;
  readonly name: string;
  readonly email: string;
}

export interface HttpFormDataMultipleProps {
  readonly firstName: string;
  readonly secondName: string;
}

// ---------------------------------------------------------------------
// 2. Component Implementations
// ---------------------------------------------------------------------

/**
 * Demonstrates creating a FormData instance and adding ordinary string fields.
 */
export const HttpFormDataBasicExample: FC<HttpFormDataBasicProps> = ({
  name,
  email,
}: HttpFormDataBasicProps): ReactNode => {
  const formData: FormData = new FormData();

  formData.append("name", name);
  formData.append("email", email);

  const storedName: FormDataEntryValue | null = formData.get("name");

  const storedEmail: FormDataEntryValue | null = formData.get("email");

  return (
    <section>
      <h3>Creating FormData fields</h3>

      <p>Name: {storedName?.toString() ?? "Missing"}</p>

      <p>Email: {storedEmail?.toString() ?? "Missing"}</p>
    </section>
  );
};

/**
 * Demonstrates that append() preserves an existing value and adds another
 * value under the same field name.
 */
export const HttpFormDataAppendExample: FC<HttpFormDataAppendProps> = ({
  firstValue,
  secondValue,
}: HttpFormDataAppendProps): ReactNode => {
  const formData: FormData = new FormData();

  formData.append("tag", firstValue);
  formData.append("tag", secondValue);

  const values: FormDataEntryValue[] = formData.getAll("tag");

  return (
    <section>
      <h3>append() preserves multiple values</h3>

      <ul>
        {values.map((value: FormDataEntryValue, index: number): ReactNode => (
          <li key={`${value.toString()}-${index}`}>{value.toString()}</li>
        ))}
      </ul>
    </section>
  );
};

/**
 * Demonstrates that set() replaces every existing value associated with the
 * specified field name.
 */
export const HttpFormDataSetExample: FC<HttpFormDataSetProps> = ({
  initialValue,
  replacementValue,
}: HttpFormDataSetProps): ReactNode => {
  const formData: FormData = new FormData();

  formData.append("status", initialValue);
  formData.append("status", "another-value");

  formData.set("status", replacementValue);

  const values: FormDataEntryValue[] = formData.getAll("status");

  return (
    <section>
      <h3>set() replaces existing values</h3>

      <p>Number of stored values: {values.length}</p>

      <p>Final value: {values[0]?.toString() ?? "Missing"}</p>
    </section>
  );
};

/**
 * Demonstrates reading FormData values with get(). A returned File or Blob
 * must be handled differently from an ordinary string value.
 */
export const HttpFormDataGetExample: FC<HttpFormDataGetProps> = ({ name, email }: HttpFormDataGetProps): ReactNode => {
  const formData: FormData = new FormData();

  formData.append("name", name);
  formData.append("email", email);

  const nameValue: FormDataEntryValue | null = formData.get("name");

  const emailValue: FormDataEntryValue | null = formData.get("email");

  const nameType: string =
    typeof nameValue === "string"
      ? "string"
      : nameValue instanceof File
        ? "File"
        : nameValue instanceof Blob
          ? "Blob"
          : "missing";

  return (
    <section>
      <h3>Reading FormData values</h3>

      <p>Name: {nameValue?.toString() ?? "Missing"}</p>

      <p>Email: {emailValue?.toString() ?? "Missing"}</p>

      <p>Name value type: {nameType}</p>
    </section>
  );
};

/**
 * Demonstrates adding a File object to FormData. File values are transmitted
 * as multipart file parts when the FormData is used as a request body.
 */
export const HttpFormDataFileExample: FC<HttpFormDataFileProps> = ({
  fileName,
  fileContent,
}: HttpFormDataFileProps): ReactNode => {
  const file: File = new File([fileContent], fileName, {
    type: "text/plain",
  });

  const formData: FormData = new FormData();

  formData.append("file", file);

  const storedFile: FormDataEntryValue | null = formData.get("file");

  const fileDetails: string = storedFile instanceof File ? `${storedFile.name} (${storedFile.size} bytes)` : "No file";

  return (
    <section>
      <h3>Adding a File to FormData</h3>

      <p>Stored file: {fileDetails}</p>
    </section>
  );
};

/**
 * Demonstrates adding a Blob with an explicit filename. FormData can associate
 * a filename with a Blob when the optional third append() argument is supplied.
 */
export const HttpFormDataBlobExample: FC<HttpFormDataBlobProps> = ({
  content,
  fileName,
}: HttpFormDataBlobProps): ReactNode => {
  const blob: Blob = new Blob([content], {
    type: "text/plain",
  });

  const formData: FormData = new FormData();

  formData.append("document", blob, fileName);

  const storedValue: FormDataEntryValue | null = formData.get("document");

  const description: string =
    storedValue instanceof File ? `${storedValue.name} (${storedValue.type})` : "No file value";

  return (
    <section>
      <h3>Adding a Blob with a filename</h3>

      <p>{description}</p>
    </section>
  );
};

/**
 * Demonstrates passing FormData directly to a Fetch Request. The browser
 * generates the multipart boundary and the corresponding Content-Type value.
 */
export const HttpFormDataRequestExample: FC<HttpFormDataRequestProps> = ({
  url,
  name,
  email,
}: HttpFormDataRequestProps): ReactNode => {
  const formData: FormData = new FormData();

  formData.append("name", name);
  formData.append("email", email);

  const request: Request = new Request(url, {
    method: "POST",
    body: formData,
  });

  const contentType: string | null = request.headers.get("Content-Type");

  return (
    <section>
      <h3>Using FormData as a Fetch request body</h3>

      <p>Content-Type: {contentType ?? "Not available"}</p>

      <p>The multipart boundary is generated by the Fetch implementation.</p>
    </section>
  );
};

/**
 * Demonstrates retrieving every value associated with a repeated FormData
 * field using getAll().
 */
export const HttpFormDataMultipleExample: FC<HttpFormDataMultipleProps> = ({
  firstName,
  secondName,
}: HttpFormDataMultipleProps): ReactNode => {
  const formData: FormData = new FormData();

  formData.append("name", firstName);
  formData.append("name", secondName);

  const names: FormDataEntryValue[] = formData.getAll("name");

  return (
    <section>
      <h3>Reading repeated fields with getAll()</h3>

      <ol>
        {names.map((value: FormDataEntryValue, index: number): ReactNode => (
          <li key={`${value.toString()}-${index}`}>{value.toString()}</li>
        ))}
      </ol>
    </section>
  );
};

// ---------------------------------------------------------------------
// 3. Main Container Component
// ---------------------------------------------------------------------

const HttpFormDataContainer: FC = (): ReactNode => {
  return (
    <main>
      <h1>HTTP Form Data</h1>

      <h2>1. Creating FormData fields</h2>
      <HttpFormDataBasicExample name="John Doe" email="john.doe@example.com" />

      <h2>2. append() preserves multiple values</h2>
      <HttpFormDataAppendExample firstValue="react" secondValue="typescript" />

      <h2>3. set() replaces existing values</h2>
      <HttpFormDataSetExample initialValue="pending" replacementValue="complete" />

      <h2>4. Reading FormData values</h2>
      <HttpFormDataGetExample name="John Doe" email="john.doe@example.com" />

      <h2>5. Adding a File to FormData</h2>
      <HttpFormDataFileExample fileName="example.txt" fileContent="Example file content." />

      <h2>6. Adding a Blob with a filename</h2>
      <HttpFormDataBlobExample fileName="document.txt" content="Example document content." />

      <h2>7. Using FormData as a Fetch request body</h2>
      <HttpFormDataRequestExample url="https://example.com/api/upload" name="John Doe" email="john.doe@example.com" />

      <h2>8. Reading repeated fields with getAll()</h2>
      <HttpFormDataMultipleExample firstName="John Doe" secondName="Jane Doe" />
    </main>
  );
};

export default HttpFormDataContainer;

// ---------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------
// - FormData represents key-value pairs for form submissions.
// - FormData supports string, Blob, and File values.
// - append() adds another value without removing existing values.
// - set() replaces all existing values for a field name.
// - get() returns the first value associated with a field name.
// - getAll() returns every value associated with a field name.
// - File is a Blob subtype that also carries file metadata.
// - A Blob can be supplied with an explicit filename when appended to FormData.
// - Passing FormData as a Fetch request body produces multipart/form-data encoding.
// - The multipart boundary should be generated by the browser rather than manually assigned.
// - FormData is suitable for forms that combine ordinary fields with uploaded files.
// - FormData and URLSearchParams represent different encoding strategies.
// - FormData values can be inspected with get(), getAll(), has(), delete(), and iteration methods.
