/**
 * HTTP Multipart
 * ==============
 *
 * Multipart is an HTTP message-body format that divides one body into multiple
 * independently encoded parts. Each part has its own headers and content,
 * allowing a single request to carry different kinds of data such as text
 * fields and binary files.
 *
 * The most common multipart media type is `multipart/form-data`, which is used
 * for HTML form submissions that contain files. A multipart/form-data body is
 * separated into parts using a boundary parameter included in the
 * Content-Type header. The same boundary value is used between the encoded
 * parts in the body.
 *
 * When a FormData object is supplied as a Fetch request body, the browser
 * generates the multipart encoding and its boundary automatically. Application
 * code should not manually assign `Content-Type: multipart/form-data` in this
 * situation because the boundary parameter must match the body generated by
 * the browser.
 *
 * Each multipart part can contain headers such as Content-Disposition and
 * Content-Type followed by the part's content. For form uploads,
 * Content-Disposition commonly contains a `name` parameter identifying the
 * form field and a `filename` parameter when the part represents a file.
 *
 * Multipart is different from `application/x-www-form-urlencoded`. URL-encoded
 * forms represent textual key-value pairs in one encoded sequence, while
 * multipart bodies preserve separate parts and can transport binary content.
 *
 * Multipart boundaries are delimiters, not arbitrary application data. The
 * encoding process must ensure that the boundary can be used unambiguously to
 * identify part boundaries. Browser-managed FormData encoding handles this
 * requirement automatically.
 */

import { type FC, type ReactNode } from "react";

// ---------------------------------------------------------------------
// 1. Interface Definitions
// ---------------------------------------------------------------------

export interface HttpMultipartBasicProps {
  readonly fieldName: string;
  readonly fieldValue: string;
}

export interface HttpMultipartFileProps {
  readonly fieldName: string;
  readonly fileName: string;
  readonly fileContent: string;
}

export interface HttpMultipartFileTypeProps {
  readonly fileName: string;
  readonly fileContent: string;
  readonly contentType: string;
}

export interface HttpMultipartMultipleProps {
  readonly name: string;
  readonly email: string;
  readonly fileName: string;
  readonly fileContent: string;
}

export interface HttpMultipartRequestProps {
  readonly url: string;
  readonly name: string;
  readonly email: string;
}

export interface HttpMultipartBoundaryProps {
  readonly boundary: string;
}

export interface HttpMultipartPartProps {
  readonly fieldName: string;
  readonly value: string;
  readonly contentType: string;
}

export interface HttpMultipartDifferenceProps {
  readonly fieldName: string;
  readonly value: string;
}

// ---------------------------------------------------------------------
// 2. Component Implementations
// ---------------------------------------------------------------------

/**
 * Demonstrates the structure of a multipart/form-data field using FormData.
 */
export const HttpMultipartBasicExample: FC<HttpMultipartBasicProps> = ({
  fieldName,
  fieldValue,
}: HttpMultipartBasicProps): ReactNode => {
  const formData: FormData = new FormData();

  formData.append(fieldName, fieldValue);

  const value: FormDataEntryValue | null = formData.get(fieldName);

  return (
    <section>
      <h3>Multipart form field</h3>

      <p>Field name: {fieldName}</p>

      <p>Field value: {value?.toString() ?? "Missing"}</p>
    </section>
  );
};

/**
 * Demonstrates adding a File to FormData. The File becomes a separate
 * multipart part when the FormData object is encoded as an HTTP request body.
 */
export const HttpMultipartFileExample: FC<HttpMultipartFileProps> = ({
  fieldName,
  fileName,
  fileContent,
}: HttpMultipartFileProps): ReactNode => {
  const file: File = new File([fileContent], fileName, {
    type: "text/plain",
  });

  const formData: FormData = new FormData();

  formData.append(fieldName, file);

  const value: FormDataEntryValue | null = formData.get(fieldName);

  const description: string = value instanceof File ? `${value.name} (${value.size} bytes)` : "No file";

  return (
    <section>
      <h3>Multipart file part</h3>

      <p>Field name: {fieldName}</p>

      <p>File: {description}</p>
    </section>
  );
};

/**
 * Demonstrates assigning a media type to a File so that the corresponding
 * multipart part carries an appropriate Content-Type value.
 */
export const HttpMultipartFileTypeExample: FC<HttpMultipartFileTypeProps> = ({
  fileName,
  fileContent,
  contentType,
}: HttpMultipartFileTypeProps): ReactNode => {
  const file: File = new File([fileContent], fileName, {
    type: contentType,
  });

  const formData: FormData = new FormData();

  formData.append("file", file);

  const value: FormDataEntryValue | null = formData.get("file");

  const storedType: string = value instanceof File ? value.type : "Unknown";

  return (
    <section>
      <h3>Multipart file content type</h3>

      <p>File name: {fileName}</p>

      <p>Content-Type: {storedType}</p>
    </section>
  );
};

/**
 * Demonstrates a multipart request containing both ordinary form fields and a
 * file part.
 */
export const HttpMultipartMultipleExample: FC<HttpMultipartMultipleProps> = ({
  name,
  email,
  fileName,
  fileContent,
}: HttpMultipartMultipleProps): ReactNode => {
  const file: File = new File([fileContent], fileName, {
    type: "text/plain",
  });

  const formData: FormData = new FormData();

  formData.append("name", name);
  formData.append("email", email);
  formData.append("file", file);

  const nameValue: FormDataEntryValue | null = formData.get("name");

  const emailValue: FormDataEntryValue | null = formData.get("email");

  const fileValue: FormDataEntryValue | null = formData.get("file");

  return (
    <section>
      <h3>Multiple multipart parts</h3>

      <p>Name: {nameValue?.toString() ?? "Missing"}</p>

      <p>Email: {emailValue?.toString() ?? "Missing"}</p>

      <p>File: {fileValue instanceof File ? fileValue.name : "Missing"}</p>
    </section>
  );
};

/**
 * Demonstrates that Fetch generates the multipart Content-Type and boundary
 * when FormData is supplied directly as the request body.
 */
export const HttpMultipartRequestExample: FC<HttpMultipartRequestProps> = ({
  url,
  name,
  email,
}: HttpMultipartRequestProps): ReactNode => {
  const formData: FormData = new FormData();

  formData.append("name", name);
  formData.append("email", email);

  const request: Request = new Request(url, {
    method: "POST",
    body: formData,
  });

  const contentType: string | null = request.headers.get("Content-Type");

  return (
    <section>
      <h3>Browser-generated multipart boundary</h3>

      <p>Content-Type: {contentType ?? "Not available"}</p>

      <p>Fetch supplies the multipart boundary when FormData is used as the request body.</p>
    </section>
  );
};

/**
 * Demonstrates the conceptual boundary parameter used to separate multipart
 * parts. The boundary shown here is illustrative and is not manually assigned
 * to a browser-managed FormData request.
 */
export const HttpMultipartBoundaryExample: FC<HttpMultipartBoundaryProps> = ({
  boundary,
}: HttpMultipartBoundaryProps): ReactNode => {
  const contentType: string = `multipart/form-data; boundary=${boundary}`;

  return (
    <section>
      <h3>Multipart boundary</h3>

      <p>Content-Type: {contentType}</p>

      <p>Boundary: {boundary}</p>

      <p>The boundary separates individual multipart parts in the encoded body.</p>
    </section>
  );
};

/**
 * Demonstrates the metadata associated with an individual multipart part.
 */
export const HttpMultipartPartExample: FC<HttpMultipartPartProps> = ({
  fieldName,
  value,
  contentType,
}: HttpMultipartPartProps): ReactNode => {
  const contentDisposition: string = `form-data; name="${fieldName}"`;

  return (
    <section>
      <h3>Multipart part headers</h3>

      <dl>
        <dt>Content-Disposition</dt>
        <dd>{contentDisposition}</dd>

        <dt>Content-Type</dt>
        <dd>{contentType}</dd>

        <dt>Content</dt>
        <dd>{value}</dd>
      </dl>
    </section>
  );
};

/**
 * Demonstrates the difference between URL-encoded form data and multipart
 * form data. The two formats use different body encodings.
 */
export const HttpMultipartDifferenceExample: FC<HttpMultipartDifferenceProps> = ({
  fieldName,
  value,
}: HttpMultipartDifferenceProps): ReactNode => {
  const urlEncoded: URLSearchParams = new URLSearchParams();

  urlEncoded.set(fieldName, value);

  const multipart: FormData = new FormData();

  multipart.append(fieldName, value);

  const urlEncodedRequest: Request = new Request("https://example.com/api/form", {
    method: "POST",
    body: urlEncoded,
  });

  const multipartRequest: Request = new Request("https://example.com/api/form", {
    method: "POST",
    body: multipart,
  });

  return (
    <section>
      <h3>URL-encoded versus multipart encoding</h3>

      <p>URL-encoded Content-Type: {urlEncodedRequest.headers.get("Content-Type")}</p>

      <p>Multipart Content-Type: {multipartRequest.headers.get("Content-Type")}</p>

      <p>
        URL-encoded forms are suited to textual key-value data, while multipart forms can contain separate file and text
        parts.
      </p>
    </section>
  );
};

// ---------------------------------------------------------------------
// 3. Main Container Component
// ---------------------------------------------------------------------

const HttpMultipartContainer: FC = (): ReactNode => {
  return (
    <main>
      <h1>HTTP Multipart</h1>

      <h2>1. Creating a multipart form field</h2>
      <HttpMultipartBasicExample fieldName="name" fieldValue="John Doe" />

      <h2>2. Adding a file as a multipart part</h2>
      <HttpMultipartFileExample fieldName="file" fileName="example.txt" fileContent="Example file content." />

      <h2>3. Assigning a content type to a multipart file</h2>
      <HttpMultipartFileTypeExample
        fileName="example.txt"
        fileContent="Example text content."
        contentType="text/plain"
      />

      <h2>4. Combining fields and files in one multipart body</h2>
      <HttpMultipartMultipleExample
        name="John Doe"
        email="john.doe@example.com"
        fileName="example.txt"
        fileContent="Example file content."
      />

      <h2>5. Letting Fetch generate the multipart boundary</h2>
      <HttpMultipartRequestExample url="https://example.com/api/upload" name="John Doe" email="john.doe@example.com" />

      <h2>6. Understanding the multipart boundary</h2>
      <HttpMultipartBoundaryExample boundary="example-boundary-123" />

      <h2>7. Understanding multipart part headers</h2>
      <HttpMultipartPartExample fieldName="name" value="John Doe" contentType="text/plain" />

      <h2>8. Comparing URL-encoded and multipart form data</h2>
      <HttpMultipartDifferenceExample fieldName="name" value="John Doe" />
    </main>
  );
};

export default HttpMultipartContainer;

// ---------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------
// - Multipart HTTP bodies contain multiple independently encoded parts.
// - multipart/form-data is commonly used for HTML forms that include files.
// - Each multipart body uses a boundary to separate its parts.
// - Multipart parts can contain their own headers and content.
// - Content-Disposition commonly identifies a form field with a name parameter.
// - File parts can also include a filename parameter in Content-Disposition.
// - FormData can combine ordinary string fields with File or Blob values.
// - Fetch generates the multipart boundary when FormData is used as a request body.
// - Application code should not manually set Content-Type for a browser-managed FormData request.
// - URL-encoded form data is primarily suited to textual key-value pairs.
// - Multipart form data can transport both textual fields and binary file content.
// - A multipart boundary must correspond to the delimiters used in the encoded body.
